---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-lvm"
  git_branch: "master"
  galaxy_id: '4402'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [Logical Volume
    Manager](https://en.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)) lets
    you manage your disk space in a more elastic way, separating physical hard
    disks from the logical volumes.

    This Ansible role lets you configure `/etc/lvm/lvm.conf` configuration
    file, as well as gives you a set of variables which can be used to manage
    LVM logical volumes, automatically create filesystems on them and mount
    them as needed.

