---

dependencies: []

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Manage radvd (IPv6 router advertisement daemon)'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system
  - networking

