---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-mailman"
  git_branch: "master"
  galaxy_id: "1574"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.mailman` Ansible role can be used to create and manage mailing
    lists using [GNU Mailman](http://list.org/) package.
    
    By default the role provides configuration for `debops.postfix` role to
    configure the SMTP server integration, as well as `debops.nginx` role to
    configure access to the web control panel.

