---

dependencies:

  - role: debops.secret

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage Mailman, Mailing List Manager'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - web
    - mailman


