---

- include: apt_cacher_ng.yml

- include: docker_gen.yml

- include: nginx.yml

- include: snmpd.yml

- include: monit.yml

- include: dovecot.yml

- include: tftpd.yml

- include: samba.yml

- include: tgt.yml

- include: mariadb_server.yml

- include: mariadb.yml

- include: mysql.yml

- include: postgresql_server.yml

- include: postgresql.yml

- include: elasticsearch.yml

- include: memcached.yml

- include: redis.yml

- include: reprepro.yml

- include: smstools.yml

- include: salt.yml

- include: fail2ban.yml

