---

- name: Add upstream PostgreSQL APT key
  apt_key:
    id: '7FCC7D46ACCC4CF8'
    state: 'present'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else "hkp://pool.sks-keyservers.net" }}'
  when: postgresql_server_upstream|d() and postgresql_server_upstream
  tags: [ 'role::postgresql_server:packages' ]

- name: Add upstream PostgreSQL APT repository
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
    state: 'present'
    update_cache: True
  when: postgresql_server_upstream|d() and postgresql_server_upstream
  tags: [ 'role::postgresql_server:packages' ]

- name: Get default PostgreSQL version
  environment:
    LC_ALL: 'C'
  shell: "apt-cache policy postgresql | grep -E '^\\s+Candidate:\\s+' | awk '{print $2}' | cut -d+ -f1"
  register: postgresql_server_register_version
  changed_when: False
  tags: [ 'role::postgresql_server:packages', 'role::postgresql_server:config',
          'role::postgresql_server:auto_backup' ]

- name: Set default PostgreSQL version variable
  set_fact:
    postgresql_server_version: '{{ ansible_local.postgresql.version
                                   if (ansible_local|d() and ansible_local.postgresql|d() and
                                       ansible_local.postgresql.version|d())
                                   else postgresql_server_register_version.stdout }}'
  tags: [ 'role::postgresql_server:packages', 'role::postgresql_server:config',
          'role::postgresql_server:auto_backup' ]

- include: install_postgresql.yml
  tags: [ 'role::postgresql_server:packages' ]

- name: Count number of currently configured clusters
  set_fact:
    postgresql_server_fact_cluster_count: '{{ (postgresql_server_clusters|length|int) * 1 }}'
  tags: [ 'role::postgresql_server:config' ]

- name: Get current maximum shared memory value
  shell: cat /proc/sys/kernel/shmmax
  register: postgresql_server_register_sysctl_shmmax
  changed_when: False
  tags: [ 'role::postgresql_server:config' ]

- include: manage_clusters.yml

- include: secure_installation.yml

- include: manage_autopostgresqlbackup.yml
  when: postgresql_server_autopostgresqlbackup|d() and postgresql_server_autopostgresqlbackup
  tags: [ 'role::postgresql_server:auto_backup' ]

- name: Make sure that Ansible local fact directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save PostgreSQL local facts
  template:
    src: 'etc/ansible/facts.d/postgresql.fact.j2'
    dest: '/etc/ansible/facts.d/postgresql.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: postgresql_server_register_local_facts
  tags: [ 'role::postgresql_server:config' ]

- name: Re-read local facts if they have been changed
  action: setup
  when: postgresql_server_register_local_facts|d() and
        postgresql_server_register_local_facts.changed
  tags: [ 'role::postgresql_server:config' ]

