---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-etc_services"
  git_branch: "master"
  galaxy_id: "1563"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    The `debops.etc_services` role can be used to "reserve" or "register" a
    service port in the `/etc/services` file. Service ports configured this way can
    appear as named entries in many command outputs, such as `iptables --list`
    or `netstat --listening --program`. You can also have convenient database
    of reserved and free ports on a particular host, and reference ports by
    their names in firewall configuration files.

