---

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski, Robin Schneider'
  description: 'Manage service definitions in /etc/services'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - networking
    - system

