---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-subnetwork"
  git_branch: "master"
  galaxy_id: "2128"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    `debops.subnetwork` is an Ansible role that creates and manages a local
    network behind a bridge interface. It could also manage internal router
    interfaces to a LAN. You can specify an IPv4 subnet and one or more
    IPv6 subnets to configure it, the role will automatically configure basic
    forwarding in any firewall and NAT for the IPv4 network.

