---

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Configure LAN with IPv4/NAT and IPv6 network support'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
  - system
  - networking
