---

- name: Get upstream APT GPG key
  apt_key:
    id: '9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else "hkp://pool.sks-keyservers.net" }}'
    state: 'present'
  when: nodejs_upstream|d() and nodejs_upstream

- name: Configure upstream APT repository
  apt_repository:
    repo: '{{ nodejs_upstream_repository }}'
    state: 'present'
    update_cache: True
  when: nodejs_upstream|d() and nodejs_upstream

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - nodejs_base_packages
    - nodejs_packages

- name: Install packages when not installing from upstream
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  when: not nodejs_upstream|d()
  with_flattened:
    - nodejs_distribution_packages

- name: Install npm global packages
  npm:
    name: '{{ item.name | default(item) }}'
    state: '{{ item.state | default("present") }}'
    version: '{{ item.version | default(omit) }}'
    production: '{{ item.production | default(omit) }}'
    global: True
  with_items: nodejs_npm_global_packages

