---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-gitlab_ci_runner"
  git_branch: "master"
  galaxy_id: "1568"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [GitLab CI Runner](https://github.com/gitlabhq/gitlab-ci-runner/) is
    a helper Ruby program which is used by
    [GitLab CI](https://about.gitlab.com/gitlab-ci/) service to run continuous
    integration tests. It should be installed on a separate host (or multiple
    hosts) or even in a LXC or OpenVZ container and is designed to be easily
    reinstalled if necessary. You will need a GitLab CI instance to use
    Runners, which can be installed and configured using `debops.gitlab_ci`
    role.

