---

- name: Create required system groups
  group:
    name: '{{ item }}'
    state: 'present'
    system: True
  with_items:
    - '{{ rstudio_server_group }}'
    - '{{ rstudio_server_auth_group }}'

- name: Create system account for RStudio Server
  user:
    name: '{{ rstudio_server_user }}'
    group: '{{ rstudio_server_group }}'
    home: '{{ rstudio_server_home }}'
    shell: '/bin/false'
    comment: 'RStudio Server'
    createhome: False
    system: True
    state: 'present'

- name: Install RStudio Server
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: rstudio_server_packages

- name: Configure RStudio Server
  template:
    src: 'etc/rstudio/{{ item }}.j2'
    dest: '/etc/rstudio/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: [ 'rserver.conf', 'rsession.conf' ]
  notify: [ 'Verify rstudio-server' ]

