---

# Configuration for php5-fpm pool
librenms_php5_pool:
  enabled: True
  name: 'librenms'
  user: '{{ librenms_user }}'
  group: '{{ librenms_group }}'

# nginx configuration - PHP5 upstream
librenms_nginx_upstream_php5:
  enabled: True
  name: 'php5_librenms'
  type: 'php5'
  php5: 'librenms'

# nginx configuration - LibreNMS
librenms_nginx_server:
  by_role: 'debops.librenms'
  enabled: True
  type: 'php5'
  name: '{{ librenms_domain }}'
  root: '{{ librenms_install_path + "/html" }}'
  filename: 'debops.librenms'
  access_policy: '{{ librenms_nginx_access_policy }}'
  auth_basic_realm: '{{ librenms_nginx_auth_realm }}'
  php5: 'php5_librenms'

  location:
    '@librenms': |
      rewrite ^api/v0(.*)$ /api_v0.php/$1 last;
      rewrite ^(.+)$ /index.php/$1 last;

    '/': |
      try_files $uri $uri/ @librenms;

