---

dependencies:
  - role: debops.ferm

  - role: debops.postfix
    postfix_dependent_maincf:
      - param: 'mailbox_transport'
        value: '{{ dovecot_postfix_transport }}'
        capability: 'local'
    when: (dovecot_dependencies is defined and dovecot_dependencies) and
          (dovecot_postfix_transport is defined and dovecot_postfix_transport) and
          'lmtp' in dovecot_protocols
    tags: postfix

galaxy_info:
  author: 'Reto Gantenbein'
  description: 'Configure Dovecot IMAP/POP3 service'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system
