---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-rsnapshot"
  git_branch: "master"
  galaxy_id: '2937'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.rsnapshot` role allows you to manage a backup host which will use
    [rsnapshot](http://www.rsnapshot.org/) to create remote backups of other
    hosts. You can let Ansible configure both the central backup "clients",
    which run `rsnapshot` and store backups, as well as the "servers" which the
    clients connect to, which run `rsync` in read-only mode on `root` accounts.
    
    You can also configure `rsnapshot` clients to backup external hosts which
    are not managed by Ansible, but you will need to set up the connection (SSH
    access, `rrsync` script) yourself on the server side.

