---

allow_duplicates: True

dependencies:
  - role: debops.secret

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Helper role to create backported packages in Debian or Ubuntu'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - development
  - packaging
  - system

