---

- name: Create directory for htpasswd files
  file:
    path: '{{ nginx_private_path }}'
    state: 'directory'
    owner: 'root'
    group: '{{ nginx_user }}'
    mode: '0750'

- name: Remove htpasswd files if requested
  file:
    dest: '{{ nginx_private_path + "/" + item.name }}'
    state: 'absent'
  with_items: '{{ nginx_htpasswd }}'
  when: ((nginx_htpasswd is defined and nginx_htpasswd) and
         (item.name is defined or item.name) and
         (item.delete is defined and item.delete))

- name: Manage users in htpasswd files
  htpasswd:
    path: '{{ nginx_private_path + "/" + item.0.name }}'
    name: '{{ item.1 }}'
    password: '{{ lookup("password", nginx_htpasswd_secret_path + "/" + item.0.name + "/" + item.1) }}'
    state: '{{ item.0.state | default("present") }}'
    owner: 'root'
    group: '{{ nginx_user }}'
    mode: '0640'
  with_subelements:
    - '{{ nginx_htpasswd }}'
    - 'users'
  when: ((nginx_htpasswd is defined and nginx_htpasswd) and
         (item.0.name is defined and item.0.name) and
         (item.1 is defined and item.1) and
         (item.0.delete is undefined or (item.0.delete is defined and not item.0.delete)))

