---

- name: Make sure configuration directory exists
  file:
    path: '/etc/nginx/conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Remove nginx maps if requested
  file:
    dest: '/etc/nginx/conf.d/map_{{ item.name }}.conf'
    state: 'absent'
  with_items: '{{ nginx_maps + nginx_default_maps + nginx_dependent_maps }}'
  notify: [ 'Test nginx and reload' ]
  when: ((item.name is defined and item.name) and
         (item.delete is defined and item.delete))

- name: Configure nginx maps
  template:
    src: 'etc/nginx/conf.d/map.conf.j2'
    dest: '/etc/nginx/conf.d/map_{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ nginx_maps + nginx_default_maps + nginx_dependent_maps }}'
  notify: [ 'Test nginx and reload' ]
  when: ((item.name is defined and item.name) and
         (item.delete is undefined or (item.delete is defined and not item.delete)))

- name: Remove nginx upstreams if requested
  file:
    dest: '/etc/nginx/conf.d/upstream_{{ item.name }}.conf'
    state: 'absent'
  with_items: '{{ nginx_upstreams + nginx_default_upstreams + nginx_dependent_upstreams }}'
  notify: [ 'Test nginx and reload' ]
  when: ((item.name is defined and item.name) and
         (item.delete is defined and item.delete))

- name: Configure nginx upstreams
  template:
    src: 'etc/nginx/conf.d/upstream_{{ item.type | default("default") }}.conf.j2'
    dest: '/etc/nginx/conf.d/upstream_{{ item.name }}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: '{{ nginx_upstreams + nginx_default_upstreams + nginx_dependent_upstreams }}'
  notify: [ 'Test nginx and reload' ]
  when: ((item.name is defined and item.name) and
         (item.delete is undefined or (item.delete is defined and not item.delete)))

- name: Remove custom nginx configuration if requested
  file:
    dest: '/etc/nginx/conf.d/{{ item.filename | default("custom_" + item.name + ".conf") }}'
    state: 'absent'
  with_items: [ '{{ nginx_custom_config }}' ]
  notify: [ 'Test nginx and reload' ]
  when: ((nginx_custom_config is defined and nginx_custom_config) and
         (item.name is defined and item.name) and
         (item.delete is defined and item.delete))

- name: Add custom nginx configuration
  template:
    src: 'etc/nginx/conf.d/custom.conf.j2'
    dest: '/etc/nginx/conf.d/{{ item.filename | default("custom_" + item.name + ".conf") }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: [ '{{ nginx_custom_config }}' ]
  notify: [ 'Test nginx and reload' ]
  when: ((nginx_custom_config is defined and nginx_custom_config) and
         (item.name is defined and item.name) and
         (item.delete is undefined or (item.delete is defined and not item.delete)))

