---

dependencies:

  - role: debops.secret

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and configure ISC DHCP Server'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - networking
  - system

