---

# ---- OpenLDAP BaseDN configuration ----

# DNS domain name which will be used for OpenLDAP BaseDN
slapd_domain: '{{ ansible_domain }}'

# BaseDN value of the OpenLDAP server
slapd_basedn: '{{ "dc=" + slapd_domain.split(".") | join(",dc=") }}'

# Specify database backend to use
slapd_backend: '{{ "hdb" if (ansible_distribution_release in [ "wheezy", "precise" ])
                         else "mdb" }}'

# Length of passwords set on administrator accounts
slapd_password_length: '128'

# Log level (see slapd-config(5) for detauls)
slapd_log_level: 'none'

# Default services enabled in /etc/default/slapd (change requires restart)
slapd_default_services: [ 'ldap:///', 'ldaps:///', 'ldapi:///' ]


# ---- Network access to OpenLDAP server ----

# Lists of hosts or CIDR networks which are allowed to access slapd service. If
# none are specified, any host can connect to OpenLDAP server
slapd_allow: []
slapd_group_allow: []
slapd_host_allow: []

# Default setting in /etc/hosts.allow if no hosts are specified in above lists
slapd_tcpwrappers_default: 'ALL'

# Deny anonymous bind to the server by default and require authentication.
# Set to True to allow anonymous bind.
slapd_anonymous_bind: False


# ---- slapd system configuration ----

# List of system groups to grant to 'openldap' user. 'ssl-cert' group is
# required for access to private keys
slapd_append_groups: [ 'ssl-cert' ]

# Create snapshots of LDAP database periodically
slapd_snapshot: True

# Snapshot period: daily, weekly
slapd_snapshot_period: 'weekly'


# ---- PKI / TLS and certificates ----

# Enable or disable support for certificates (using debops.pki)
slapd_pki: '{{ (ansible_local.pki.enabled
                if (ansible_local|d() and ansible_local.pki|d() and
                    ansible_local.pki.enabled|d())
                else True) | bool }}'

# Base PKI directory
slapd_pki_path: '{{ (ansible_local.pki.base_path
                     if (ansible_local|d() and ansible_local.pki|d() and
                         ansible_local.pki.base_path|d())
                     else "/etc/pki") }}'

# Default PKI realm used by OpenLDAP
slapd_pki_realm: '{{ (ansible_local.pki.realm
                      if (ansible_local|d() and ansible_local.pki|d() and
                          ansible_local.pki.realm|d())
                      else "system") }}'

# Default CA certificate, server certificate and key used by OpenLDAP server
slapd_pki_ca: 'CA.crt'
slapd_pki_crt: 'default.crt'
slapd_pki_key: 'default.key'

# Specify the Diffie-Hellman parameter set to use. See ``debops.dhparam`` role
# for more details.
slapd_dhparam_set: 'default'

# Absolute path to file with Diffie-Hellman parameters.
slapd_dhparam_file: '{{ (ansible_local.dhparam[slapd_dhparam_set]
                         if (ansible_local|d() and ansible_local.dhparam|d() and
                             ansible_local.dhparam[slapd_dhparam_set]|d())
                         else "") }}'


# TLS cipher suite required by the server
slapd_pki_ciphers: 'SECURE256:-VERS-SSL3.0'


# ---- Administrator accounts & passwords ----

# slapd passwords cannot be directly generated by Ansible; they are handled in
# separate tasks during runtime. Here you can change the location of passwords
# in debops.secret storage if needed, for example to point several slapd
# servers to the same set of passwords.

# ==== cn=admin,cn=config ====

# Base path to BaseDN administrator password
slapd_config_admin_basepw: '{{ secret + "/credentials/" + ansible_fqdn + "/slapd/cn=config/cn=admin,cn=config" }}'

# Plaintext password of BaseDN administrator
slapd_config_admin_password: '{{ slapd_config_admin_basepw + ".password" }}'

# Hash of BaseDN administrator password
slapd_config_admin_hash: '{{ slapd_config_admin_basepw + ".hash" }}'

# ==== BaseDN administrator ====

# Distinguished Name of main administrator account
slapd_basedn_admin: '{{ "cn=admin," + slapd_basedn }}'

# Base path to BaseDN administrator password
slapd_basedn_admin_basepw: '{{ secret + "/slapd/credentials/" + slapd_basedn + "/" + slapd_basedn_admin }}'

# Plaintext password of BaseDN administrator
slapd_basedn_admin_password: '{{ slapd_basedn_admin_basepw + ".password" }}'

# Hash of BaseDN administrator password
slapd_basedn_admin_hash: '{{ slapd_basedn_admin_basepw + ".hash" }}'

# Location of the Ansible password file for LDAP admin access
# (see 'debops.secret' role for more details)
slapd_basedn_admin_ansible_password: '{{ secret_ldap_admin_password }}'


# ---- ldapscripts configuration ----

# See templates/etc/ldapscripts/ldapscripts.conf for more information about
# these variables

# Enable ldapscripts support (install and configure ldapscripts)
slapd_ldapscripts: False

# LDAP server to configure
slapd_ldapscripts_server: 'ldap://localhost'

# Default BaseDN to use in ldapscripts
slapd_ldapscripts_suffix: '{{ slapd_basedn }}'

# Oranizational Units for Groups, Users and Machines
slapd_ldapscripts_gsuffix: 'ou=Groups'
slapd_ldapscripts_usuffix: 'ou=Users'
slapd_ldapscripts_msuffix: 'ou=Machines'

# BindDN admin account and file with password
slapd_ldapscripts_binddn: '{{ slapd_basedn_admin }}'
slapd_ldapscripts_bindpwdfile: '/etc/ldapscripts/ldapscripts.passwd'

# Where to look for admin account password
slapd_ldapscripts_password_lookup: '{{ slapd_basedn_admin_password }}'

# Groups, User and Machine  start IDs
slapd_ldapscripts_gidstart: '10000'
slapd_ldapscripts_uidstart: '10000'
slapd_ldapscripts_midstart: '20000'

# Group membership management
# Possible values: posixGroup, groupOfNames, groupOfUniqueNames
slapd_ldapscripts_gclass: 'posixGroup'
slapd_ldapscripts_gdummymember: 'uid=dummy,$USUFFIX,$SUFFIX'

# User password generation
slapd_ldapscripts_passwordgen: 'pwgen'


# ---- Custom LDAP schema ----

# These files will be automatically loaded into cn=config configuration
# database by a helper script. You need to specify absolute paths to *.ldif
# files. Default set can be found in '/etc/ldap/schema/'
slapd_ldap_schema:

    # Additional attributes and classes for LDAP Name Service
  - '/usr/local/etc/ldap/schema/ldapns.ldif'

    # Support for SSH Public Key lookup in LDAP
  - '/usr/local/etc/ldap/schema/openssh-lpk.ldif'


# ---- LDAP index configuration ----

# List of index entries configured on the server
slapd_ldap_index: '{{ slapd_ldap_index_default }}'

# Default list of indices
slapd_ldap_index_default:

  - 'objectClass eq'
  - 'cn eq,pres'
  - 'gn eq,pres'
  - 'sn eq,pres'
  - 'uid eq'
  - 'uidNumber eq'
  - 'gidNumber eq'
  - 'memberUid eq'
  - 'authorizedService eq'
  - 'host eq'
  - 'entryCSN eq'
  - 'entryUUID eq'


# ---- LDAP connection security ----

# List of security rules enabled on the OpenLDAP server
slapd_ldap_security: '{{ slapd_ldap_security_tls
                         if slapd_pki | bool
                         else slapd_ldap_security_default }}'

# Don't require encryption for all connections
slapd_ldap_security_default: []

# Require encryption for all connections
slapd_ldap_security_tls:

  - 'simple_bind=128'
  - 'update_ssf=128'
  - 'ssf=128'
  - 'tls=128'


# ---- LDAP Access Control List ----

# List of olcAccess attributes configured on the server
slapd_ldap_access_control_list: '{{ slapd_ldap_access_control_list_default }}'

# Security Strength Factor used in ACL entries
slapd_acl_tls_ssf: '{{ "tls_ssf=128 ssf=128"
                       if slapd_pki | bool else "" }}'

# Default LDAP ACL. Order of entries is important!
slapd_ldap_access_control_list_default:

  - |
    to attrs=userPassword,shadowLastChange
    by {{ slapd_acl_tls_ssf }} self write
    by {{ slapd_acl_tls_ssf }} anonymous auth
    by {{ slapd_acl_tls_ssf }} dn="{{ slapd_basedn_admin }}" write
    by * none

  - |
    to attrs=uid,uidNumber,gidNumber,homeDirectory,loginShell
    by {{ slapd_acl_tls_ssf }} self read
    by {{ slapd_acl_tls_ssf }} dn="{{ slapd_basedn_admin }}" write
    by {{ slapd_acl_tls_ssf }} users read

  - |
    to dn.base=""
    by {{ slapd_acl_tls_ssf }} * read

  - |
    to *
    by {{ slapd_acl_tls_ssf }} self read
    by {{ slapd_acl_tls_ssf }} dn.subtree="ou=Machines,{{ slapd_basedn }}" read
    by {{ slapd_acl_tls_ssf }} dn="{{ slapd_basedn_admin }}" write
    by * none

# A prefix number added to the filename which helps order the firewall rules.
slapd_ferm_weight: '40'

# Firewall configuration managed by ``ferm``.
slapd_ferm_dependent_rules:

  - type: 'accept'
    protocol: [ 'tcp', 'udp' ]
    dport: [ 'ldap', 'ldaps' ]
    saddr: '{{ slapd_allow + slapd_group_allow + slapd_host_allow }}'
    accept_any: True
    weight: '{{ slapd_ferm_weight }}'
    role: 'slapd'

# Configuration of TCP Wrappers.
slapd_tcpwrappers_dependent_allow:

  - daemon: 'slapd'
    client: '{{ slapd_allow + slapd_group_allow + slapd_host_allow }}'
    default: '{{ slapd_tcpwrappers_default }}'
    weight: '50'
    filename: 'slapd_dependent_allow'
    comment: 'Allow connections to OpenLDAP'

