---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-gitlab_ci"
  git_branch: "master"
  galaxy_id: "1567"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [GitLab CI](https://about.gitlab.com/gitlab-ci/) is a continuous
    integration service based around [GitLab](https://about.gitlab.com/). It
    uses a GitLab instance for authentication and access to git repositories
    (can be managed using `debops.gitlab` role) and
    [GitLab CI Runner](https://github.com/gitlabhq/gitlab-ci-runner/) service
    to run the tests (can be installed using `debops.gitlab_ci_runner` role).

