---

dependencies:

  - role: debops.secret

  - role: debops.etc_services
    etc_services_dependent_list:

      - name: '{{ gitlab_ci_user }}'
        port: '{{ gitlab_ci_unicorn_port }}'
        comment: 'GitLab CI'

  - role: debops.ruby

  - role: debops.redis

  - role: debops.mysql
    when: (gitlab_ci_dependencies is defined and gitlab_ci_dependencies) and
          (gitlab_ci_database is defined and gitlab_ci_database and gitlab_ci_database == 'mysql')

    mysql_databases:
      - name: '{{ gitlab_ci_database_config[gitlab_ci_database].database }}'
        state: 'present'

    mysql_users:
      - name: '{{ gitlab_ci_database_config[gitlab_ci_database].username }}'
        host: '{{ gitlab_ci_database_config[gitlab_ci_database].hostname }}'
        priv: '{{ gitlab_ci_database_config[gitlab_ci_database].database }}.*:ALL'
        state: 'present'

  - role: debops.postgresql
    when: (gitlab_ci_dependencies is defined and gitlab_ci_dependencies) and
          (gitlab_ci_database is defined and gitlab_ci_database and gitlab_ci_database == 'postgresql')

  - role: debops.nginx
    nginx_servers: [ '{{ gitlab_ci_nginx_server }}' ]
    nginx_upstreams: [ '{{ gitlab_ci_nginx_upstream }}' ]
    when: (gitlab_ci_dependencies is defined and gitlab_ci_dependencies)
    tags: nginx

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install, upgrade and manage GitLab CI instance'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - development
  - web

