---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:owncloud', 'depend-of::owncloud', 'type::dependency:hard' ]

galaxy_info:

  author: 'Maciej Delmanowski, Hartmut Goebel'
  description: 'Install and manage ownCloud instance'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - cloud
    - privat cloud
    - file sharing
    - calender
    - contacts
    - web
