---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-redis"
  git_branch: "master"
  galaxy_id: "1592"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Nick Janetakis'
      url: ''
      email: 'nick.janetakis@gmail.com'
      twitter: 'nickjanetakis'
      github: 'nickjj'

    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    `debops.redis` role allows you to easily setup infrastructure capable of
    running and managing 1 or more Redis servers. It is completely self healing
    with Redis Sentinel and supports replication seamlessly.
    
    Few features available in this role:
    
    - seamless master/slave replication;
    - throw together a master + n slaves + n sentinel setup in about 10 lines of YAML
      (most of those lines would be adding your hosts to the inventory);
    - your configs are idempotent, even when redis rewrites them;
    - pretty much every redis config value is tweakable;
    - you can easily use this role as a dependency in your other roles;

