---

dependencies:
  - role: debops.secret

  - role: debops.apt_preferences
    tags: apt_preferences
    apt_preferences_dependent_list:
      - package: 'redis-server'
        backports: [ 'wheezy' ]
        reason: 'Critical bugs in older versions - http://download.redis.io/redis-stable/00-RELEASENOTES'
        by_role: 'debops.redis'

  - role: debops.etc_services
    etc_services_dependency_list:
      - name: 'redis-server'
        port: '{{ redis_port }}'
      - name: 'redis-sentinel'
        port: '{{ redis_sentinel_port }}'

  - role: debops.ferm
    ferm_input_group_list:
      - type: 'dport_accept'
        dport: ['redis-server']
        saddr: '{{ redis_server_allow }}'
      - type: 'dport_accept'
        dport: ['redis-sentinel']
        saddr: '{{ redis_sentinel_allow }}'

galaxy_info:
  author: 'Nick Janetakis'
  description: 'Install and manage Redis cluster'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - 'database:nosql'
  - 'system'

