---

dependencies:

  - role: debops.ferm
    tags: [ 'depend::ferm', 'depend::ferm:dnsmasq', 'depend-of::dnsmasq', 'type::dependency' ]

  - role: debops.tcpwrappers
    tags: [ 'depend::tcpwrappers', 'depend::tcpwrappers:dnsmasq', 'depend-of::dnsmasq', 'type::dependency' ]

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and configure dnsmasq, DNS, DHCP and PXE/TFTP service'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - development
  - packaging
  - system

