---

- name: Install Redis server
  apt: pkg=redis-server state=present install_recommends=False

- name: Detect Redis version
  shell: redis-server -v | awk '{print $3}'
  changed_when: False
  register: register_redis_version

- name: Create Redis paths
  file: path={{ item }} state=directory owner=redis group=redis mode=0755
  with_items:
    - '{{ redis_dir }}'
    - '{{ redis_run_state }}'
    - '{{ redis_log }}'
    - '{{ redis_script }}'

- include: sentinel.yml
  when: redis_sentinel_hosts_group in group_names

- name: Flush the handlers so Sentinel is up and running before the servers
  meta: flush_handlers

# Always install Redis server unless the host exists in the sentinel group
# and it's not standalone.
- include: server.yml
  when: (not redis_sentinel_standalone and
        redis_sentinel_hosts_group in group_names) or True

- name: Stop Redis Server
  service: name=redis-server state=stopped enabled=no
  when: redis_sentinel_standalone and
        redis_hosts_group in group_names and
        redis_sentinel_hosts_group in group_names
