---

dependencies:
  - role: debops.etc_services
    etc_services_dependency_list:
      - name: 'elasticsearch-multicast'
        port: '{{ elasticsearch_discovery_multicast_port }}'

  - role: debops.ferm
    ferm_input_group_list:
      - type: 'dport_accept'
        dport: ['{{ elasticsearch_node_port | replace("-", ":") }}']
        saddr: '{{ elasticsearch_node_allow }}'
      - type: 'dport_accept'
        dport: ['{{ elasticsearch_http_port | replace("-", ":") }}']
        saddr: '{{ elasticsearch_http_allow }}'
      - type: 'dport_accept'
        protocol: [ 'udp' ]
        dport: ['elasticsearch-multicast']
        saddr: '{{ elasticsearch_multicast_allow }}'

  - role: debops.java
    tags: java
    when: elasticsearch_role_dependencies is defined and
          'java' in elasticsearch_role_dependencies

galaxy_info:
  author: 'Nick Janetakis'
  description: 'Install and manage Elasticsearch database clusters'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - clustering
  - database
  - database:nosql

