---
# Default variables
# =================

# ----------
#   Packages
# ----------

# .. envvar:: rsyslog_packages
#
# Install set of standard packages
rsyslog_packages: [ 'rsyslog', 'logrotate' ]


# --------------
#   Manage pools
# --------------

# .. envvar:: rsyslog_manage_pools
#
# Should rsyslog role manage server pools?
rsyslog_manage_pools: True


# .. envvar:: rsyslog_pools
#
# List of managed pools.
rsyslog_pools: [ '{{ rsyslog_pool_cron }}' ]


# .. envvar:: rsyslog_pool_cron
#
# Default rsyslog pool, explanation of variables can be found
# in :file:`templates/etc/rsyslog.d/pool.conf.j2`.
# Everything commented out is optional.
rsyslog_pool_cron:
  enabled: True
  name: '49-cron'
  options: |
    cron.*		/var/log/cron.log
    & stop

    :msg, contains, "pam_unix(cron:session): session opened for user" /var/log/cron.log
    & stop

    :msg, contains, "pam_unix(cron:session): session closed for user" /var/log/cron.log
    & stop
