---

# Specify version of Ruby to install:
# - 'apt':      (default) will install Ruby packages automatically depending on
#               what's available in APT at the time
#
# - 'backport': will enable backporting of packages from the next distribution
#               (currently on Debian Wheezy it's required to install Ruby 2.1
#               packages)
#
ruby_version: 'apt'

# Install 'rubygems-integration' package (on older distributions it might not
# exist)
ruby_gems_integration: True

# Lists of additional APT packages to install with Ruby packages (for all
# hosts, group of hosts, specific host or role dependency). You can use these
# lists to for example install packaged gems.
ruby_packages: []
ruby_group_packages: []
ruby_host_packages: []
ruby_dependent_packages: []

# Lists of Ruby gems to install from RubyGems.org. Role will use conservative
# approach and not install or update any gems, that are already installed, either
# via gem or via APT.
ruby_default_gems: [ 'bundler' ]
ruby_gems: []
ruby_group_gems: []
ruby_host_gems: []
ruby_dependent_gems: []

