---

# Ansible does not support management of multiple MariaDB / MySQL from one user
# account, so if a database server is installed locally, we will avoid messing
# with local root account to not lose the control over it.
- name: Check if database server is installed
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'mariadb-server' 'mysql-server' 'percona-server-server' | grep -v '^$'
  register: mariadb_register_version
  changed_when: False
  failed_when: False

- name: Add MariaDB APT GPG key
  apt_key:
    state: 'present'
    id: '{{ mariadb_upstream_key }}'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver|d())
                   else "hkp://pool.sks-keyservers.net" }}'
  when: mariadb_flavor in [ 'mariadb_upstream' ]

- name: Add MariaDB APT repository
  apt_repository:
    repo: '{{ mariadb_upstream_repository }}'
    state: 'present'
    update_cache: True
  when: mariadb_flavor in [ 'mariadb_upstream' ]

- name: Add Percona APT GPG key
  apt_key:
    state: 'present'
    id: '1C4CBDCDCD2EFD2A'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver|d())
                   else "hkp://pool.sks-keyservers.net" }}'
  when: mariadb_flavor in [ 'percona' ]

- name: Add Percona APT repository
  apt_repository:
    repo: 'deb http://repo.percona.com/apt {{ ansible_distribution_release }} main'
    state: 'present'
    update_cache: True
  when: mariadb_flavor in [ 'percona' ]

- name: Check if local database port is open
  command: nc -z localhost {{ mariadb_port }}
  register: mariadb_register_tunnel
  when: not mariadb_register_version.stdout
  failed_when: False
  changed_when: False

- name: Override delegation if tunnel is detected
  set_fact:
    mariadb_delegate_to: '{{ mariadb_server|d("undefined") }}'
  when: (not mariadb_register_version.stdout|d(False) and
         (mariadb_register_tunnel|d() and mariadb_register_tunnel.rc == 0))

- name: Override configuration if local server is detected
  set_fact:
    mariadb_server: 'localhost'
    mariadb_client: 'localhost'
  when: (mariadb_register_version.stdout|d(False) or
         (mariadb_register_tunnel|d() and mariadb_register_tunnel.rc == 0))

- name: Install database client packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ mariadb_base_packages }}'
    - '{{ mariadb_packages_map[mariadb_flavor] }}'
    - '{{ mariadb_packages }}'

- name: Configure database client defaults
  template:
    src: 'etc/mysql/conf.d/client.cnf.j2'
    dest: '/etc/mysql/conf.d/client.cnf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: mariadb_server|d(False)

- name: Make sure that local fact directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save MariaDB local facts
  template:
    src: 'etc/ansible/facts.d/mariadb.fact.j2'
    dest: '/etc/ansible/facts.d/mariadb.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: mariadb_register_local_facts

- name: Re-read local facts if they have been changed
  action: setup
  when: mariadb_register_local_facts|d() and
        mariadb_register_local_facts.changed

- name: Manage database contents
  include: 'manage_contents.yml'
  when: (mariadb_server|d(False) and mariadb_delegate_to)
  tags: [ 'role::mariadb:contents' ]

