---

- name: Restart nfs-common
  service:
    name: 'nfs-common'
    state: 'restarted'
  when: ansible_distribution == 'Debian'

- name: Restart nfs-kernel-server
  service:
    name: 'nfs-kernel-server'
    state: 'restarted'

- name: Reload NFS exports
  command: exportfs -ra

