---

- name: Enable Linux firmware packages on hosts that require it
  set_fact:
    apt__conditional_firmware: '{{ apt__conditional_firmware_packages[ansible_distribution] }}'
  when: ('firmware' in apt__conditional_whitelist and
         ansible_system == 'Linux' and ansible_form_factor in ['Rack Mount Chassis'])

- name: Enable irqbalance on multi-core systems
  set_fact:
    apt__conditional_irqbalance: [ 'irqbalance' ]
  when: ('irqbalance' in apt__conditional_whitelist and ansible_processor_cores >= 2 and
         (ansible_virtualization_role is undefined or ansible_virtualization_role not in [ 'guest' ]))

- name: Enable uptimed on hardware systems
  set_fact:
    apt__conditional_uptimed: [ 'uptimed' ]
  when: ('uptimed' in apt__conditional_whitelist and
         (ansible_virtualization_role is undefined or ansible_virtualization_role not in [ 'guest' ]))

- name: Combine conditional packages into one list
  set_fact:
    apt__conditional_packages: '{{
      (apt__conditional_firmware   | d([]) | list ) +
      (apt__conditional_irqbalance | d([]) | list) +
      (apt__conditional_uptimed    | d([]) | list) }}'

- name: Install requested packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_flattened:
    - '{{ apt__base_packages }}'
    - '{{ apt__packages }}'
    - '{{ apt__group_packages }}'
    - '{{ apt__host_packages }}'
    - '{{ apt__conditional_packages }}'

