---

- name: Install apticron and apt-listchanges
  apt:
    pkg: '{{ item }}'
    state: 'latest'
    install_recommends: no
  with_flattened: '{{ apt__update_notification_packages | list }}'
  when: (apt__update_notifications|d() | bool)

- name: Configure apticron and apt-listchanges
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_items:
    - 'etc/apt/listchanges.conf'
    - 'etc/apticron/apticron.conf'
  when: (apt__update_notifications|d() | bool)

- name: Remove apticron and apt-listchanges
  apt:
    pkg: '{{ item }}'
    state: 'absent'
    purge: yes
  with_flattened: '{{ apt__update_notification_packages | list }}'
  when: not (apt__update_notifications|d() | bool)



