---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-tftpd"
  git_branch: "master"
  galaxy_id: '3480'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This Ansible role can configure a standalone TFTP server using `tftpd-hpa`
    package. It can be used to serve files for embedded devices or serve iPXE
    files from [debops.ipxe](https://github.com/debops/ansible-ipxe/) role to
    other hosts on the network.


