---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-dokuwiki"
  git_branch: "master"
  galaxy_id: '3240'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role will install and manage [DokuWiki](http://dokuwiki.org/),
    a text-based and easy to use wiki written in PHP5

