---

dependencies:

  - role: debops.php5
    php5_packages: [ 'php5-gmp', 'php5-curl', 'php5-mcrypt', 'php-net-ipv4', 'php5-ldap' ]
    php5_pools: [ '{{ dokuwiki_php5_pool }}' ]

  - role: debops.nginx
    nginx_servers: [ '{{ dokuwiki_nginx_server }}' ]
    nginx_upstreams: [ '{{ dokuwiki_nginx_upstream_php5 }}' ]
    tags: nginx

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install DokuWiki, a text-based wiki written in PHP5'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - web

