---

- name: Stop networks if requested
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_connections[item.uri | d(libvirt_uri)] }}'
    state: 'inactive'
  with_items: libvirt_networks
  become: False
  when: ((item.name|d() and item.name) and
         (item.state is defined and item.state in [ 'inactive', 'undefined', 'absent' ]))

- name: Undefine networks if requested
  virt_net:
    name: '{{ item.name }}'
    uri: '{{ libvirt_connections[item.uri | d(libvirt_uri)] }}'
    state: 'absent'
  with_items: libvirt_networks
  become: False
  when: ((item.name|d() and item.name) and
         (item.state is defined and item.state in [ 'undefined', 'absent' ]))

- name: Define networks
  virt_net:
    name: '{{ item.name }}'
    xml: '{{ lookup("template", "lookup/network/" + item.type + ".xml.j2") }}'
    uri: '{{ libvirt_connections[item.uri | d(libvirt_uri)] }}'
    state: 'present'
  with_items: libvirt_networks
  become: False
  when: ((item.name|d() and item.name) and
         (item.state is undefined or item.state not in [ 'undefined', 'absent' ]) and
         (item.interface_present is undefined or
          (item.interface_present in ansible_interfaces and not item.uri|d())))

- name: Start networks if not started
  virt_net:
    name: '{{ item.name }}'
    state: 'active'
    uri: '{{ libvirt_connections[item.uri | d(libvirt_uri)] }}'
  with_items: libvirt_networks
  become: False
  when: ((item.name|d() and item.name) and
         (item.state is undefined or item.state in [ 'active' ]) and
         (item.interface_present is undefined or
          (item.interface_present in ansible_interfaces and not item.uri|d())))

- name: Set autostart attribute on networks
  virt_net:
    name: '{{ item.name }}'
    autostart: '{{ "yes" if (item.autostart is undefined or item.autostart|d()) else "no" }}'
    uri: '{{ libvirt_connections[item.uri | d(libvirt_uri)] }}'
  with_items: libvirt_networks
  become: False
  when: ((item.name|d() and item.name) and
         (item.state is undefined or item.state not in [ 'undefined', 'absent' ]) and
         (item.interface_present is undefined or
          (item.interface_present in ansible_interfaces and not item.uri|d())))

