- src: debops.apt

- src: debops.apt_cacher_ng

- src: debops.apt_install

- src: debops.apt_preferences

- src: debops.atd

- src: debops.auth

- src: debops.backporter

- src: debops.bootstrap

- src: debops.boxbackup

- src: debops.console

- src: debops.core

- src: debops.cryptsetup

- src: debops.debops

- src: debops.dhcpd

- src: debops.dhparam

- src: debops.dnsmasq

- src: debops.docker

- src: debops.docker_gen

- src: debops.dokuwiki

- src: debops.dovecot

- src: debops.elasticsearch

- src: debops.etc_services

- src: debops.etherpad

- src: debops.fail2ban

- src: debops.fcgiwrap

- src: debops.ferm

- src: debops.gitlab

- src: debops.gitlab_ci

- src: debops.gitlab_ci_runner

- src: debops.gitlab_runner

- src: debops.gitusers

- src: debops.golang

- src: debops.grub

- src: debops.hwraid

- src: debops.ifupdown

- src: debops.ipxe

- src: debops.iscsi

- src: debops.java

- src: debops.kvm

- src: debops.librenms

- src: debops.libvirt

- src: debops.libvirtd

- src: debops.logrotate

- src: debops.lvm

- src: debops.lxc

- src: debops.mailman

- src: debops.mariadb

- src: debops.mariadb_server

- src: debops.memcached

- src: debops.monit

- src: debops.monkeysphere

- src: debops.mysql

- src: debops.nfs

- src: debops.nginx

- src: debops.nodejs

- src: debops.ntp

- src: debops.openvz

- src: debops.owncloud

- src: debops.php5

- src: debops.phpipam

- src: debops.phpmyadmin

- src: debops.pki

- src: debops.postfix

- src: debops.postgresql

- src: debops.postgresql_server

- src: debops.preseed

- src: debops.radvd

- src: debops.rails_deploy

- src: debops.redis

- src: debops.reprepro

- src: debops.resources

- src: debops.rsnapshot

- src: debops.rstudio_server

- src: debops.rsyslog

- src: debops.ruby

- src: debops.salt

- src: debops.samba

- src: debops.secret

- src: debops.sftpusers

- src: debops.sks

- src: debops.slapd

- src: debops.smstools

- src: debops.snmpd

- src: debops.sshd

- src: debops.sshkeys

- src: debops.stunnel

- src: debops.subnetwork

- src: debops.swapfile

- src: debops.tcpwrappers

- src: debops.tftpd

- src: debops.tgt

- src: debops.tinc

- src: debops.unattended_upgrades

- src: debops.users

