---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-java"
  git_branch: "master"
  galaxy_id: "1571"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Nick Janetakis'
      url: ''
      email: 'nick.janetakis@gmail.com'
      twitter: 'nickjanetakis'
      github: 'nickjj'

  synopsis: |
    This role installs OpenJDK Java packages. It is useful as a dependency of
    other roles.

