---

- name: Configure shared memory kernel parameters
  sysctl:
    sysctl_file: '{{ console_sysctl_file }}'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: True
  with_dict: '{{ console_sysctl_kernel_shm_values }}'
  when: console_sysctl_kernel_shm_values|d()

- name: Configure sys_admin kernel parameters
  sysctl:
    sysctl_file: '{{ console_sysctl_file }}'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: True
  with_dict: '{{ console_sysctl_sys_admin_values }}'
  when: (console_sysctl_sys_admin_values|d() and
         (ansible_local|d() and ((ansible_local.root|d() and 'ignore-cap12s' in ansible_local.root.flags) or
          (ansible_local.cap12s|d() and (not ansible_local.cap12s.enabled | bool or
           (ansible_local.cap12s.enabled | bool and 'cap_sys_admin' in ansible_local.cap12s.list))))))

