---

- name: Enforce root group
  group:
    name: 'root'
    gid: '0'
    system: True
    state: 'present'

- name: Enforce root user account
  user:
    name: 'root'
    state: 'present'
    group: 'root'
    home: '/root'
    uid: '0'
    groups: ''
    append: False
    system: True

- name: Enforce root password
  user:
    name: 'root'
    state: 'present'
    createhome: False
    password: '{{ console_root_password }}'
    update_password: 'always'
  when: console_root_password is defined and console_root_password

- name: Enforce root shell
  user:
    name: 'root'
    createhome: False
    shell: '{{ console_root_shell }}'
  when: console_root_shell is defined and console_root_shell

- name: Enforce root home permissions
  file:
    path: '/root'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

