---

- name: Enable system news bulletin for all users
  template:
    src: 'etc/profile.d/sysnews.sh.j2'
    dest: '/etc/profile.d/sysnews.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: console_sysnews_global|d() and
        console_sysnews_global|bool

- name: Generate persistent news files
  template:
    src: 'var/lib/sysnews/news.j2'
    dest: '/var/lib/sysnews/{{ item.key }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_dict: console_sysnews_entries
  when: item.key is defined and item.key

- name: Update list of persistent files
  template:
    src: 'var/lib/sysnews/noexpire.j2'
    dest: '/var/lib/sysnews/.noexpire'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: console_sysnews_entries is defined and
        console_sysnews_entries

