---

# Should monkeysphere be enabled? Disabled by default due to required manual
# preparations, see: http://web.monkeysphere.info/getting-started-admin/
monkeysphere: False

# Should monkeysphere automatically publish new keys to Web of Trust?
monkeysphere_autopublish: False

# List of identity certifiers to add automatically at first setup (omit 0x)
monkeysphere_default_identity_certifiers: False

# At what minute each hour monkeysphere should update the user authorized_keys?
monkeysphere_update_minute: '42'

# Keyserver to use (default frontend from 'sks' role). You might want to setup
# an internal-only frontend or backend to mitigate availability problems
monkeysphere_keyserver: 'keyserver.{{ ansible_domain }}'

# Default keyserver from monkeysphere configuration, public GPG Web of Trust
#monkeysphere_keyserver: 'pool.sks-keyservers.net'

# Should monkeysphere check the keyserver on each connection?
monkeysphere_check_keyserver: 'false'

# Log verbosity (SILENT, ERROR, INFO, VERBOSE, DEBUG)
monkeysphere_log_level: 'INFO'

# System user that controls the monkeysphere GPG keyring
monkeysphere_user: 'monkeysphere'

# Look for user ids in system-wide directory
monkeysphere_authorized_user_ids: '/etc/monkeysphere/authorized_user_ids/%u'

# Don't combine user's authorized_keys, sshd supports multiple files
monkeysphere_raw_authorized_keys: 'none'

