---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-atd"
  git_branch: "master"
  galaxy_id: '5670'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `at` and `batch` commands can be used to compliment `cron` and run
    one-off tasks either at a specified time, or when the host CPU utilization is
    on a low enough level.
    
    The `debops.atd` role can be used to configure `atd` service, including
    randomized load average threshold and randomized time between batch job
    execution, as well as access control to the `at` and `batch` commands by
    the users.

