---

# Install either the 'apt' or 'backport' version of Golang
#   'apt'      whatever version is available through apt on your OS/distro
#   'backport' for when you're building the backport on your build server
#
# Versions for a few popular distros:
#   Debian Wheezy: 1.0.2 -> backport version is 1.3.1
#   Debian Jessie: 1.3.1
#   Ubuntu Trusty: 1.2.1
golang_version: 'apt'

