---

# ----  Paths ----

redis_dir: '/var/lib/redis'
redis_run_state: '/var/run/redis'
redis_log: '/var/log/redis'
redis_script: '/usr/local/lib/redis'

redis_config: '/etc/redis/redis.conf'
redis_sentinel_config: '/etc/redis/sentinel.conf'
redis_custom_config: '/etc/redis/redis-ansible.conf'
redis_custom_sentinel_config: '/etc/redis/sentinel-ansible.conf'


# ---- General ----

redis_daemonize: 'yes'
redis_pidfile: '{{ redis_run_state }}/redis-server.pid'
redis_logfile: '""'
redis_syslog_enabled: 'no'
redis_syslog_ident: 'redis'
redis_syslog_facility: 'USER'
redis_databases: 16


# ---- Sentinel ----

redis_sentinel_pidfile: '{{ redis_run_state }}/redis-sentinel.pid'
redis_sentinel_syslog_ident: 'sentinel'


# ---- Snapshotting ----

redis_rdbcompression: 'yes'
redis_rdbchecksum: 'yes'
redis_dbfilename: 'dump.rdb'


# ---- Replication ----

redis_slave_serve_stale_data: 'yes'
redis_repl_disable_tcp_nodelay: 'no'


# ---- Limits ----

redis_maxmemory: '{{ (ansible_memtotal_mb | int * redis_maxmemory_multiplier) | round | int }}mb'
redis_maxmemory_samples: 3


# ---- Append only mode ----

redis_appendfilename: 'appendonly.aof'
redis_appendfsync: 'everysec'
redis_no_appendfsync_on_rewrite: 'no'
redis_auto_aof_rewrite_percentage: 100
redis_auto_aof_rewrite_min_size: '64mb'


# ---- LUA scripting ----

redis_lua_time_limit: 5000
