---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-mariadb_server"
  git_branch: "master"
  galaxy_id: '4187'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [MariaDB](http://mariadb.org/) is a popular relational SQL database that
    was forked from MySQL server. Ansible roles `debops.mariadb` and
    `debops.mariadb_server` allow you to manage a MariaDB server and / or
    access it remotely from other hosts.
    
    `debops.mariadb_server` role is the "server" part - it installs
    `mariadb-server` Debian package, and configures access to the database from
    local `root` account. After that, you can use `debops.mariadb` role to
    manage databases and user accounts on the server.

