---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-samba"
  git_branch: "master"
  galaxy_id: "1597"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role installs and configures a Samba 3 file server with a default file
    share. You can configure your own shares using inventory variables.

