---

- name: Check if Network Manager is installed
  stat:
    path: '/usr/sbin/NetworkManager'
  register: ifupdown_nmstatus

- name: Enable Network Manager support if installed
  set_fact:
    ifupdown_networkmanager: 'installed'
  when: ifupdown_nmstatus.stat.exists
