---

- name: Check if default configuration is static
  shell: grep 'static' /etc/network/interfaces | grep -Eq "^[^#]"
  register: ifupdown_register_static_config
  changed_when: False
  failed_when: False
  always_run: True

- name: Enable static default configuration if detected
  set_fact:
    ifupdown_static_config: 'static'
  when: ifupdown_register_static_config.rc == 0

