---

- name: Move interfaces out of the way before reversion
  command: rm -f /etc/network/interfaces removes=/etc/network/interfaces.dpkg-divert

- name: Revert original /etc/network/interfaces
  command: dpkg-divert --quiet --local --rename --remove /etc/network/interfaces
           removes=/etc/network/interfaces.dpkg-divert


