---

- name: Manage Advanced Package Manager
  hosts: [ 'debops_all_hosts', 'debops_service_apt' ]
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ apt__apt_preferences__dependent_list }}'

    - role: debops.apt
      tags: [ 'role::apt' ]

