---

- name: Install APT packages
  hosts: [ 'debops_all_hosts', 'debops_service_apt_install' ]
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ apt_install__apt_preferences__dependent_list }}'

    - role: debops.apt_install
      tags: [ 'role::apt_install' ]

