---

- name: Manage APT preferences
  hosts: [ 'debops_all_hosts', 'debops_service_apt_preferences' ]
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]

