---

- name: Install DebOps recursively
  hosts: [ 'debops_service_debops', 'debops_service_recursively',
           'debops_recursively' ]
  become: True

  roles:

    - role: debops.debops
      tags: [ 'role::debops' ]

