---

- name: Manage Elasticsearch server
  hosts: [ 'debops_service_elasticsearch_master',
           'debops_service_elasticsearch_workhorse',
           'debops_service_elasticsearch_coordinator',
           'debops_service_elasticsearch_loadbalancer',
           'debops_elasticsearch_master', 'debops_elasticsearch_workhorse',
           'debops_elasticsearch_coordinator', 'debops_elasticsearch_loadbalancer' ]
  become: True

  roles:

    - role: debops.elasticsearch
      tags: [ 'role::elasticsearch' ]

