---

- name: Manage /etc/services database
  hosts: [ 'debops_all_hosts', 'debops_service_etc_services' ]
  become: True

  roles:

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]

