---

- name: Manage GitLab CI Runner service
  hosts: [ 'debops_service_gitlab_ci_runner', 'debops_gitlab_ci_runner' ]
  become: True

  roles:

    - role: debops.gitlab_ci_runner
      tags: [ 'role::gitlab_ci_runner' ]

