---

- name: Manage users with git-shell accounts
  hosts: [ 'debops_service_gitusers', 'debops_gitusers' ]
  become: True

  roles:

    - role: debops.gitusers
      tags: [ 'role::gitusers' ]

    - role: debops.sshkeys
      tags: [ 'role::sshkeys' ]

