---

- name: Install and manage libvirtd
  hosts: [ 'debops_service_libvirtd', 'debops_libvirtd' ]
  become: True

  roles:

    - role: debops.apt_preferences
      tags: [ 'depend::apt_preferences', 'type::dependency' ]
      apt_preferences__dependent_list:
        - '{{ libvirtd__apt_preferences__dependent_list }}'

    - role: debops.ferm
      tags: [ 'depend::ferm', 'type::dependency' ]
      ferm__forward: '{{ libvirtd__ferm__forward|d() | bool }}'
      ferm__dependent_rules:
        - '{{ libvirtd__ferm__dependent_rules }}'

    - role: debops.libvirtd
      tags: [ 'role::libvirtd' ]

