---

- name: Manage Mailman service
  hosts: [ 'debops_service_mailman', 'debops_mailman' ]
  become: True

  roles:

    - role: debops.fcgiwrap
      tags: [ 'role::fcgiwrap' ]
      fcgiwrap__instances:
        - '{{ mailman__fcgiwrap__instance }}'

    - role: debops.unattended_upgrades
      tags: [ 'role::unattended_upgrades' ]
      unattended_upgrades__dependent_blacklist: '{{ mailman__unattended_upgrades__dependent_blacklist }}'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ mailman__apt_preferences__dependent_list }}'
        - '{{ nginx_apt_preferences_dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ postfix_ferm_dependent_rules }}'
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.postfix
      tags: [ 'role::postfix' ]
      postfix_dependent_lists:    '{{ mailman__postfix__dependent_lists }}'
      postfix_dependent_maincf:   '{{ mailman__postfix__dependent_maincf }}'
      postfix_dependent_mastercf: '{{ mailman__postfix__dependent_mastercf }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_servers: '{{ mailman__nginx__servers }}'

    - role: debops.mailman
      tags: [ 'role::mailman' ]

