---

- name: Manage MariaDB server
  hosts: [ 'debops_service_mariadb_server', 'debops_mariadb_server' ]
  become: True

  roles:

    - role: debops.mariadb_server
      tags: [ 'role::mariadb_server' ]

