---

- name: Manage MySQL server
  hosts: 'debops_mysql'
  become: True

  roles:

    - role: debops.mysql
      tags: mysql

    - role: debops.phpmyadmin
      when: mysql_phpmyadmin is defined and mysql_phpmyadmin
      tags: [ 'mysql', 'phpmyadmin' ]

