---

- name: Manage Network Time Protocol service
  hosts: [ 'debops_all_hosts', 'debops_service_ntp' ]
  become: True

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ ntp_ferm_dependent_rules }}'

    - role: debops.ntp
      tags: [ 'role::ntp' ]

