---

- name: Manage ownCloud service
  hosts: [ 'debops_service_owncloud', 'debops_owncloud' ]
  become: True

  roles:

    - role: debops.mariadb
      tags: [ 'role::mariadb' ]
      mariadb_users:
        - database: '{{ owncloud_database_map[owncloud_database].dbname }}'
          user: '{{ owncloud_database_map[owncloud_database].dbuser }}'
          password: '{{ owncloud_database_map[owncloud_database].dbpass }}'
      when: (owncloud_database == 'mariadb')

    - role: debops.postgresql
      postgresql_roles:
        - name: '{{ owncloud_database_name }}' # Separate role is needed when owncloud_database_name != owncloud_database_user
        - name: '{{ owncloud_database_user }}' # Password is not passed directly - it will be read for the file
      postgresql_groups:
        - roles: [ '{{ owncloud_database_user }}' ]
          groups: [ '{{ owncloud_database_name }}' ]
          database: '{{ owncloud_database_name }}'
          enabled: '{{ owncloud_database_name != owncloud_database_user }}'
      postgresql_databases:
        - name: '{{ owncloud_database_name }}'
          owner: '{{ owncloud_database_user }}'
      when: (owncloud_database == 'postgresql')
      tags: [ 'role::postgresql' ]

    - role: debops.php5
      tags: [ 'role::php5' ]
      php5_pools:
        - '{{ owncloud_php5_pool }}'

    - role: debops.apt_preferences
      tags: [ 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ nginx_apt_preferences_dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ nginx_ferm_dependent_rules }}'

    - role: debops.nginx
      tags: [ 'role::nginx' ]
      nginx_servers:
        - '{{ owncloud_nginx_server }}'
      nginx_upstreams:
        - '{{ owncloud_nginx_upstream_php5 }}'

    - role: debops.owncloud
      tags: [ 'role::owncloud' ]

