---

- name: Manage Postfix SMTP service
  hosts: [ 'debops_service_postfix' ]
  become: True

  roles:

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ postfix_ferm_dependent_rules }}'

    - role: debops.postfix
      tags: [ 'role::postfix' ]

