---

- name: Manage Redis server
  hosts: [ 'debops_service_redis', 'debops_redis' ]
  become: True

  roles:

    - role: debops.redis
      tags: [ 'role::redis' ]


- name: Manage Redis sentinel server
  hosts: [ 'debops_service_redis_sentinel', 'debops_redis_sentinel' ]
  become: True

  roles:

    - role: debops.redis
      tags: [ 'role::redis' ]

