---

- name: Manage RStudio Server
  hosts: [ 'debops_service_rstudio_server', 'debops_rstudio_server' ]
  become: True

  roles:

    - role: debops.rstudio_server
      tags: [ 'role::rstudio_server' ]

