---

- name: Manage unattended APT upgrades
  hosts: [ 'debops_all_hosts', 'debops_service_unattended_upgrades' ]
  become: True

  roles:

    - role: debops.unattended_upgrades
      tags: [ 'role::unattended_upgrades' ]

