---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-swapfile"
  git_branch: "master"
  galaxy_id: '5618'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This Ansible role lets you manage one or multiple swap files. You can also
    manage kernel parameters related to how swap is used by the system.

    Note that this role can not setup a swap file on a BTRFS filesystem.
