---

- name: Set default umask for new home directories
  lineinfile:
    dest: '/etc/login.defs'
    regexp: '^UMASK\s+'
    line: "UMASK\t\t{{ auth_shadow_umask }}"
    backup: False
    state: 'present'

