---

- name: DebOps pre_tasks hook
  include: "{{ lookup('task_src', 'auth/pre_main.yml') }}"

- name: Install auth-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: 'no'
  with_items: '{{ auth_packages }}'

- name: Ensure common system groups exist
  group:
    name: '{{ item }}'
    system: 'yes'
    state: 'present'
  with_items: '{{ auth_system_groups }}'
  when: auth_system_groups is defined and auth_system_groups

- name: Configure admin access in sudo
  template:
    src: '{{ lookup("template_src", "etc/sudoers.d/admins.j2") }}'
    dest: '/etc/sudoers.d/admins'
    owner: 'root'
    group: 'root'
    mode: '0440'
    validate: 'visudo -cf %s'
  when: auth_wheel_group is defined and auth_wheel_group

- name: Configure local account options
  include: login_passwd_shadow.yml

- name: Configure pam_cracklib
  template:
    src: 'usr/share/pam-configs/cracklib.j2'
    dest: '/usr/share/pam-configs/cracklib'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Update PAM common configuration' ]
  when: auth_cracklib is defined and auth_cracklib

- name: Configure PAM password history module
  include: pam_pwhistory.yml
  when: auth_pwhistory_remember is defined and auth_pwhistory_remember

- name: Check if /etc/ldap exists
  stat:
    path: '/etc/ldap'
  register: auth_register_etc_ldap

- include: etc_ldap_conf.yml
  when: ((auth_ldap_conf is defined and auth_ldap_conf) and
         ((auth_register_etc_ldap is defined and auth_register_etc_ldap.stat.exists) or
          (auth_nsswitch is defined and 'ldap' in auth_nsswitch)))

- include: nss_pam_ldap.yml
  when: auth_nsswitch is defined and 'ldap' in auth_nsswitch

- name: Check if libnss-mdns package is installed
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'libnss-mdns' | grep -v '^$'
  register: auth_register_mdns
  changed_when: False
  failed_when: False

- name: Configure nsswitch.conf
  template:
    src: '{{ lookup("template_src", "etc/nsswitch.conf.j2") }}'
    dest: '/etc/nsswitch.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: DebOps post_tasks hook
  include: "{{ lookup('task_src', 'auth/post_main.yml') }}"

