---

# ---- OpenVZ Cluster - global options ----

# List of hosts in OpenVZ "cluster". These hosts will exchange SSH public keys
# from their root accounts between them and record their SSH fingerprints for
# easier container migration using vzmigrate.
# By default it's all hosts in 'debops_openvz' group. You can change that by
# defining a list of hosts using their inventory_hostname variable
openvz_cluster: '{{ groups.debops_openvz }}'

# Where OpenVZ containers are being stored? This preferably should be
# a separate partition
openvz_container_storage: '/var/lib/vz'

# Default filesystem layout for new OpenVZ containers (simfs, ploop)
openvz_storage_layout: 'ploop'


# ---- root SSH keys and /root/.ssh/known_hosts ----

# SSH on root is used for container migration. OpenVZ role will exchange root
# SSH keys between all hosts in 'openvz_cluster' list.

# Key length of generated root SSH key
openvz_root_ssh_key_bits: '4096'

# List of custom hosts to add in root's ~/.ssh/known_hosts
openvz_root_ssh_known_hosts: []

# Command used to scan SSH fingerprints
openvz_root_ssh_known_hosts_command: 'ssh-keyscan -H -T 10'

# File which holds SSH host fingerprints for root account
openvz_root_ssh_known_hosts_file: '/root/.ssh/known_hosts'


# ---- Configuration file for new OpenVZ containers ----

# Default configuration file for new OpenVZ containers
openvz_configfile: 'vswap-debops'

# How many containers do you plan to setup on an OpenVZ HN?
openvz_configfile_container_count: '5'

# Disk space soft limit multiplier
openvz_configfile_diskspace_limit_multiplier: '0.7'

# Disk inodes soft limit multiplier
openvz_configfile_diskinodes_limit_multiplier: '0.9'

# VSwap multiplier
openvz_configfile_vswap_multiplier: '0.2'

# How much RAM to reserve for the operating system?
openvz_configfile_memory_padding: '256'

# Quota time limit in seconds
openvz_configfile_quotatime: '0'

# Default cpuunits for new container
openvz_configfile_cpuunits: '1000'

# Default netfilter state for new containers
# Choices: disabled, stateless, stateful, full
openvz_configfile_netfilter: 'stateful'


# ---- OpenVZ container template ----

# Default container template
openvz_template: 'debian-7.0-x86_64-minimal'

# Should OpenVZ automatically update template images?
openvz_template_update: 'yes'

# Should OpenVZ check gnupg signature of a template image?
openvz_template_signature: 'yes'

# Where to look for online for OpenVZ templates
openvz_template_prefix: 'http://download.openvz.org/template/precreated'

# List of directories with "repositories" of templates on template server
openvz_template_repos:
  - '{{ openvz_template_prefix }}'
  - '{{ openvz_template_prefix }}/contrib'

# Configure administrator account using bootstrap script
openvz_template_admin: True

# Admin account will be created as a system account (UID < 1000)
openvz_template_admin_system: True

# Name of default admin account created by the bootstrap script
openvz_template_admin_name: '{{ ansible_ssh_user if ansible_ssh_user != "root" else lookup("env","USER") }}'

# List of system groups to which admin account will be added by default
openvz_template_admin_groups: [ 'admins', 'staff', 'adm' ]

# Path to the home directory of admin account (normal account)
openvz_template_admin_home: '{{ "/home/" + openvz_template_admin_name }}'

# Path to the home directory of admin account (system account)
openvz_template_admin_system_home: '{{ ansible_local.root.home + "/" + openvz_template_admin_name }}'

# Specify administrator account home directory group
openvz_template_admin_home_group: '{{ openvz_template_admin_groups[0] }}'

# Specify permissions for administrator account home directory
openvz_template_admin_home_mode: '0750'

# Comment / GECOS field added to the admin account
openvz_template_admin_comment: 'System Administrator'

# Default shell enabled on admin account
openvz_template_admin_shell: '/bin/bash'

# Enable or disable configuration of the passwordless sudo access for
# a specified system group
openvz_template_sudo: True

# Which system group should have passwordless sudo access?
openvz_template_sudo_group: '{{ openvz_template_admin_groups[0] | default("") }}'

# Default SSH keys added on the admin account by the bootstrap script
openvz_template_admin_sshkeys: [ '{{ lookup("pipe","ssh-add -L | grep ^ssh || cat ~/.ssh/id_rsa.pub || true") }}' ]


# ---- Salt integration ----

# Enable or disable Salt integration in vzbootstrap-ansible script. SaltStack
# upstream repository will be configured in the newly create OpenVZ container
# and packages listed below will be installed
openvz_template_salt: False

# List of Salt packages to install in new hosts
openvz_template_salt_packages: [ 'salt-minion' ]

# Additional options to set for salt-minion, in YAML text block format
# Contents will be inserted into a vzbootstrap-ansible Bash script on OpenVZ
# host and echoed to /etc/salt/minion.d/ansible.conf file
openvz_template_salt_options: False


# ---- OpenVZ kernel ----

# Enable or disable kernel configuration
openvz_kernel: True

# Name of a kernel package (or metapackage) installed by openvz role
openvz_kernel_name: 'linux-image-openvz-amd64'

# Default GRUB menu entry to boot (counting from 0). When OpenVZ-enabled kernel
# is installed, it will be placed just after the official Debian kernel. Recovery
# option in GRUB should be disabled, which is the default when you use DebOps
# Debian Preseed setup
openvz_grub_default: '1'

# Where to send mail reminders and alerts from openvz role
openvz_mail_to: [ 'root@{{ ansible_domain }}' ]

# List of IPv4 iptables kernel modules to be enabled in containers by default
openvz_iptables: [ 'ipt_REJECT', 'ipt_tos', 'ipt_TOS', 'ipt_LOG', 'ip_conntrack',
                   'ipt_limit', 'ipt_multiport', 'iptable_filter', 'iptable_mangle',
                   'ipt_TCPMSS', 'ipt_tcpmss', 'ipt_ttl', 'ipt_length', 'ipt_state',
                   'iptable_nat', 'ip_nat_ftp' ]


# ---- OpenVZ APT repository configuration ----

openvz_apt_repository: 'http://download.openvz.org/debian'
openvz_apt_repository_key_url: 'http://download.openvz.org/debian/archive.key'
openvz_apt_repository_key_id: '0FCA9BAC'
openvz_apt_distribution: '{{ ansible_distribution_release }}'

