---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-dhparam"
  git_branch: "master"
  galaxy_id: '5691'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [Diffie-Hellman Key Exchange][] is a way to securely share encryption keys
    publicly between two parties. It's used in TLS and SSL connections to
    provide [Perfect Forward Secrecy][]. Unfortunately, the default DH parameters
    distributed with applications are susceptible to a [downgrade attack][].

    The `debops.dhparam` Ansible role will generate a set of strong
    Diffie-Hellman parameters on the Ansible Controller, which will be preseeded on
    remote hosts, and will be ready to use by other applications. A separate
    script can then be used on remote hosts in the background to generate new
    random DH parameters, either once or in regular intervals.

    [Diffie-Hellman Key Exchange]: https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange
    [Perfect Forward Secrecy]: https://en.wikipedia.org/wiki/Forward_secrecy
    [downgrade attack]: https://weakdh.org/

