---

dependencies:

  - role: debops.secret

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Manage one or multiple sets of Diffie-Hellman Ephemeral parameters'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.9.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - encryption
    - security
    - tls
    - ssl
    - pki
    - weakdh
    - logjam

