---

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Install and manage libvirtd.'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.8.0'

  platforms:

    - name: Ubuntu
      versions:
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
  - system
  - virtualization

