---

allow_duplicates: True

dependencies: []

galaxy_info:

  author: 'Maciej Delmanowski'
  description: 'Manage APT pins in /etc/apt/preferences.d/'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'

  platforms:

    - name: 'Ubuntu'
      versions: [ 'all' ]

    - name: 'Debian'
      versions: [ 'all' ]

  galaxy_tags:
    - system
    - apt
