---

- name: Check status of monkeysphere-authentication
  shell: monkeysphere-authentication diagnostics | grep "No Identity Certifiers found" || true
  register: monkeysphere_authentication_status
  changed_when: monkeysphere_authentication_status.rc != 0

- name: Add default identity certifiers
  shell: yes | monkeysphere-authentication add-identity-certifier {{ item }}
  with_items: monkeysphere_default_identity_certifiers
  when: monkeysphere_default_identity_certifiers is defined and
        monkeysphere_default_identity_certifiers and
        monkeysphere_authentication_status is defined and
        monkeysphere_authentication_status.stdout.startswith('! No Identity Certifiers found!')

- name: Configure automatic key update in cron
  cron: name="monkeysphere update user keys" minute={{ monkeysphere_update_minute }}
        user="root" job="/usr/sbin/monkeysphere-authentication update-users"
        cron_file=monkeysphere-authentication

