---

- include: install.yml
  when: monkeysphere is defined and monkeysphere

- include: host_setup.yml
  when: monkeysphere is defined and monkeysphere

- include: authentication_setup.yml
  when: monkeysphere is defined and monkeysphere

