---

dependencies:

  - role: debops.secret

galaxy_info:

  company: 'DebOps'
  author: 'Robin Schneider'
  description: 'Install and manage the caching HTTP proxy Apt-Cacher NG.'
  license: 'GPL-3.0'
  min_ansible_version: '1.9.0'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

  galaxy_tags:
    - system
    - proxy
    - caching
    - packages
    - apt
