---

dependencies:
  - role: debops.secret

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage PostgreSQL Server'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.9.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - 'database:sql'
  - 'system'

