---

dependencies:

  - role: debops.etc_services
    when: rstudio_server_enabled|d() and rstudio_server_enabled
    etc_services_dependent_list:

      - name: 'rstudio-server'
        port: '{{ rstudio_server_port }}'
        comment: 'RStudio Server'

  - role: debops.nginx
    when: rstudio_server_enabled|d() and rstudio_server_enabled
    nginx_servers: [ '{{ rstudio_server_nginx_server }}' ]
    tags: nginx

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Configure RStudio Server, an Integrated Development Environment for R'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.8.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
    - web

