---

- name: Display deploy.html page
  shell: cp {{ gitlab_ci_git_checkout }}/public/deploy.html {{ gitlab_ci_git_checkout }}/public/index.html
         creates={{ gitlab_ci_git_checkout }}/public/index.html

- name: Stop GitLab CI before upgrade
  service:
    name: 'gitlab-ci'
    state: 'stopped'

