---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-monkeysphere"
  git_branch: "master"
  galaxy_id: "1576"

  beta: True
  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role can be used to give SSH users the ability to login to the server
    using their PGP/GnuPG keys. This functionality is enabled using
    [Monkeysphere](http://web.monkeysphere.info/ project.
    
    At the moment role is not fully complete. Required user configuration
    functionality is in the works.

