---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-mysql"
  git_branch: "master"
  galaxy_id: "1577"

  status:
    name: "deprecated"
    note: "It has been superseded by [debops.mariadb_server](https://github.com/debops/ansible-mariadb_server)."

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    Install and manage a MySQL database. At the moment only database on
    `localhost` is supported.

    You can use this role as a dependency of another role to easily create
    databases and users for a particular application (database and user
    management is also available using Ansible inventory).

