---

dependencies:

  - role: debops.secret

  - role: debops.ferm
    ferm_input_list:

      - type: 'dport_accept'
        dport: [ 'mysql' ]
        saddr: '{{ mysql_mysqld_allow }}'
        weight: '50'
        filename: 'mysql_dependency_accept'

  - role: debops.tcpwrappers
    tcpwrappers_allow:

      - daemon: 'mysqld'
        client: '{{ mysql_mysqld_allow }}'
        weight: '50'
        filename: 'mysql_dependency_allow'
        comment: 'Allow remote connections to MySQL server'

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and manage a MySQL server'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - 'database:sql'
  - 'system'

