---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-apt"
  git_branch: "master"
  galaxy_id: "1551"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    `debops.apt` configures and manages the APT package manager in Debian and
    other derivative distributions. Specifically, it will manage:

    * The APT sources
    * The use of a APT proxy server in the network
    * Installation of custom packages specified in Ansible inventory

