---

# Base Ruby packages to install for specified Ruby version
ruby_base_packages:
  'apt':      [ 'ruby', 'libruby' ]
  'backport': [ 'ruby', 'ruby2.1', 'libruby', 'libruby2.1' ]

# Development packages to install for specified Ruby version
ruby_dev_packages:
  'apt':      [ 'ruby-dev' ]
  'backport': [ 'ruby-dev', 'ruby2.1-dev', 'ruby-all-dev' ]

ruby_gems_integration_packages:
  True: [ 'rubygems-integration' ]
  False: []

# Directory where backporter role will store generated .deb packages for later
# installation
ruby_build_cache: '/tmp/debops-backporter-ruby21-cache'

