---

dependencies:

  - role: debops.secret

  - role: debops.php5
    php5_packages: [ 'php5-mysql', 'php5-mcrypt', 'php5-gd' ]
    php5_pools: [ '{{ phpmyadmin_php5_pool }}' ]
    when: phpmyadmin_dependencies is defined and phpmyadmin_dependencies
    tags: [ 'mysql', 'phpmyadmin' ]

  - role: debops.nginx
    nginx_servers: [ '{{ phpmyadmin_nginx_server }}' ]
    nginx_upstreams: [ '{{ phpmyadmin_nginx_upstream_php5 }}' ]
    when: phpmyadmin_dependencies is defined and phpmyadmin_dependencies
    tags: [ 'mysql', 'phpmyadmin', 'nginx' ]

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and configure PHPMyAdmin on a MySQL database server'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - 'database:sql'
  - 'system'

