---

dependencies:

  - role: debops.etc_services
    etc_services_dependent_list:

      - name: 'salt-publish'
        port: '{{ salt_publish_port }}'
        comment: 'Salt Master (publish)'

      - name: 'salt-return'
        port: '{{ salt_return_port }}'
        comment: 'Salt Master (return)'

  - role: debops.ferm
    ferm_input_list:

      - type: 'dport_accept'
        dport: [ 'salt-publish', 'salt-return' ]
        saddr: '{{ salt_allow + salt_group_allow + salt_host_allow }}'
        accept_any: True
        filename: 'salt_dependency_accept'
        weight: '20'


galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Install and configure Salt master service'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system

