---

# This is a fallback default static interface configuration.
# The `debops.ifupdown` role checks if original `/etc/network/interfaces` had
# a static configuration and if true, enables this fallback with default IPv4
# interface

ifupdown_default_interfaces:

  - iface: '{{ ansible_default_ipv4.interface }}'
    inet: 'static'
    options: |
      address {{ ansible_default_ipv4.address }}
      network {{ ansible_default_ipv4.network }}
      netmask {{ ansible_default_ipv4.netmask }}
      gateway {{ ansible_default_ipv4.gateway }}
      dns-nameserver {{ ansible_default_ipv4.gateway }}

