---

# Defaults for most common configuration
# - 1 or 2 network interfaces, if exist, no auto/allow-hotplug
# - bridge on each interface configured via dhcp, only on the interfaces that
#   exist, configured automatically
# This allows you to attach virtual machines to bridges (both external and
# internal)

ifupdown_default_interfaces:

  - iface: '{{ ifupdown_external_interface }}'
    inet: 'manual'
    port_active: True

  - iface: '{{ ifupdown_internal_interface }}'
    inet: 'manual'
    port_active: True

  - iface: 'br0'
    type: 'bridge'
    port: '{{ ifupdown_external_interface }}'
    port_present: '{{ ifupdown_external_interface }}'
    port_active: True

  - iface: 'br0'
    auto: False
    allow: False
    type: 'bridge'
    inet6: 'auto'
    port_present: '{{ ifupdown_external_interface }}'
    port_active: True

  - iface: 'br1'
    type: 'bridge'
    port: '{{ ifupdown_internal_interface }}'
    port_present: '{{ ifupdown_internal_interface }}'
    port_active: True

  - iface: 'br1'
    auto: False
    allow: False
    type: 'bridge'
    inet6: 'auto'
    port_present: '{{ ifupdown_internal_interface }}'
    port_active: True

