---

# Example configuration from interfaces(5) manual

ifupdown_default_interfaces:

  - iface: '{{ ifupdown_external_interface }}'
    type: 'mapping'
    options: |
      script /usr/local/sbin/map-scheme
      map HOME {{ ifupdown_external_interface }}-home
      map WORK {{ ifupdown_external_interface }}-work

  - iface: '{{ ifupdown_external_interface }}-home'
    inet: 'static'
    auto: False
    force: True
    addresses: [ '192.168.1.1/24' ]
    options: |
      up flush-mail

  - iface: '{{ ifupdown_external_interface }}-work'
    auto: False
    force: True
    inet: 'dhcp'

  - iface: '{{ ifupdown_internal_interface }}'
    allow: 'hotplug'
    inet: 'dhcp'

