---

# Example bonding/vlan configuration from https://wiki.debian.org/NetworkConfiguration

ifupdown_default_interfaces:

  - iface: 'bond0'
    type: 'bond'
    inet: 'manual'
    options: |
      up ifconfig bond0 0.0.0.0 up
      bond_slaves {{ ifupdown_internal_interface }} {{ ifupdown_external_interface }}

  - iface: 'vlan10'
    type: 'vlan'
    weight: '10'
    inet: 'static'
    device: 'bond0'
    addresses: [ '10.10.10.12/16' ]
    gateway: '10.10.0.1'
    options: |
      dns-search hup.hu
      dns-nameservers 10.10.0.2

  - iface: 'vlan20'
    type: 'vlan'
    weight: '10'
    inet: 'static'
    device: 'bond0'
    addresses: [ '10.20.10.12/16' ]

  - iface: 'vlan30'
    type: 'vlan'
    weight: '10'
    inet: 'static'
    device: 'bond0'
    addresses: [ '10.30.10.12/16' ]

