---

# Example multiple IP address configuration from https://wiki.debian.org/NetworkConfiguration

ifupdown_default_interfaces:

  - iface: '{{ ifupdown_external_interface }}'
    filename: 'interface_{{ ifupdown_external_interface }}_multi'
    inet: 'static'
    allow: 'hotplug'
    addresses: [ '192.168.1.42/24', '192.168.1.44/24', '10.10.10.14/24' ]
    gateway: '192.168.1.1'

