---

# Example configuration from /usr/share/doc/ifenslave-2.6/examples/ethernet+wifi

ifupdown_default_interfaces:

  - iface: 'bond0'
    type: 'bond'
    options: |
      bond-slaves eth0 wlan0
      bond-mode 1
      bond-miimon 100
      bond-primary eth0

  - iface: 'wlan0'
    inet: 'manual'
    allow: 'bond0'
    options: |
      bond-give-a-chance 10
      wpa-bridge bond0
      wpa-key-mgmt WPA-PSK
      wpa-proto WPA
      wpa-group CCMP
      wpa-ssid my-ssid
      wpa-psk "my-secret-password"


