---

# Example static configuration from https://wiki.debian.org/NetworkConfiguration

ifupdown_default_interfaces:

  - iface: '{{ ifupdown_external_interface }}'
    inet: 'static'
    addresses: '192.0.2.7/24'
    gateway: '192.0.2.254'

  - iface: '{{ ifupdown_external_interface }}'
    inet6: 'static'
    auto: False
    allow: False
    addresses: '2001:db8::c0ca:leaf/64'
    gateway: '2001:db8::lead:ed:beef'

