---

# Defaults for LXC containers (configuration via dhcp)

ifupdown_default_interfaces:

  - iface: '{{ ifupdown_external_interface }}'
    port_active: True

  - iface: '{{ ifupdown_external_interface }}'
    auto: False
    allow: False
    inet6: 'auto'
    port_active: True

  - iface: '{{ ifupdown_internal_interface }}'
    port_active: True

  - iface: '{{ ifupdown_internal_interface }}'
    auto: False
    allow: False
    inet6: 'auto'
    port_active: True

