---

dependencies:

- role: debops.apt_preferences
  tags: apt_preferences
  apt_preferences_dependent_list:
    - package: 'monit'
      backports: [ 'wheezy' ]
      reason: 'Critical bugs in older versions - http://mmonit.com/monit/dist/CHANGES.txt'
      by_role: 'debops.monit'

- role: debops.etc_services
  etc_services_dependency_list:
    - name: 'monit'
      port: '{{ monit_http_port }}'

galaxy_info:
  author: 'Nick Janetakis'
  description: 'Install and configure Monit service'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - monitoring
  - system

