---

# ---- GitLab CI Runner source ----

# Address of the official GitLab CI Runner git repository to use
gitlab_ci_runner_git_repo: 'https://gitlab.com/gitlab-org/gitlab-ci-runner.git'

# Directory where GitLab CI Runner source will be cloned to
gitlab_ci_runner_git_dest: '{{ gitlab_ci_runner_home + "/src/" + gitlab_ci_runner_git_repo.split("://")[1] }}'

# Directory where GitLab CI Runner will be checked out (application directory)
gitlab_ci_runner_git_checkout: '{{ gitlab_ci_runner_home + "/gitlab-ci-runner" }}'

# Mapping of "official" version to git branches of GitLab CI Runner
gitlab_ci_runner_version_map:
  '5.0': '5-0-stable'

