---
# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ---------------------------
#   Swap file configuration
# ---------------------------

# .. envvar:: swapfile__size
#
# Default size of swap files, in MB.
swapfile__size: '{{ ((ansible_memtotal_mb|int * 2)
                     if (ansible_memtotal_mb|int <= 2048)
                     else "512") }}'


# .. envvar:: swapfile__priority
#
# Default swap file priority, from ``-1`` to ``32767``.
swapfile__priority: '-1'


# .. envvar:: swapfile__use_dd
#
# By default ``debops.swapfile`` uses the ``fallocate`` command to create the swap
# files. If you use unsupported filesystems (``ext4`` is supported) you can
# enable this variable to use ``dd`` command to create the files.
swapfile__use_dd: False


# .. envvar:: swapfile__files
#
# List of swap files. Specify either a path to a file on a filesystem, or
# a YAML dict. See :ref:`swapfile__files` for more details.
swapfile__files: [ '/swapfile' ]


# ---------------------
#   Kernel parameters
# ---------------------

# .. envvar:: swapfile__swappiness
#
# Set ``vm.swappiness`` kernel parameter.
swapfile__swappiness: '60'


# .. envvar:: swapfile__cache_pressure
#
# Set ``vm.vfs_cache_pressure`` kernel parameter.
swapfile__cache_pressure: '100'


# .. envvar:: swapfile__sysctl_file
#
# Name of the file with kernel parameters.
swapfile__sysctl_file: '/etc/sysctl.d/30-debops.swapfile.conf'


# .. envvar:: swapfile__sysctl_map
#
# YAML dictionary with kernel parameters to set. Change it to an empty dict
# to disable the kernel configuration.
swapfile__sysctl_map:
  'vm.swappiness': '{{ swapfile__swappiness }}'
  'vm.vfs_cache_pressure': '{{ swapfile__cache_pressure }}'

