---

- name: Make sure rsyslog is installed
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_flattened:
    - '{{ rsyslog_packages }}'
  when: rsyslog_packages|d()
  notify: [ 'Restart rsyslogd' ]

- include: pools.yml
  when: rsyslog_manage_pools|d() == True
