---

- name: Setup rsyslog pool configuration
  template:
    src: 'etc/rsyslog.d/pool.conf.j2'
    dest: '/etc/rsyslog.d/{{ item.name }}.conf'
    owner: '{{ item.owner   | default("root") }}'
    group: '{{ item.group   | default("root") }}'
    mode:  '{{ item.mode    | default("0644") }}'
    backup: '{{ item.backup | default("no") }}'
  with_items: '{{ rsyslog_pools }}'
  when: (item.name|d() and item.enabled|d(True) == True)
  notify: [ 'Restart rsyslogd' ]

- name: Disable rsyslog pools
  file:
    path: '/etc/rsyslog.d/{{ item.name }}.conf'
    state: 'absent'
  with_items: '{{ rsyslog_pools }}'
  when: (item.name|d() and item.enabled|d() == False)
  notify: [ 'Restart rsyslogd' ]
