---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-tcpwrappers"
  git_branch: "master"
  galaxy_id: "1604"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role can be used to manage
    [TCP Wrappers](https://en.wikipedia.org/wiki/TCP\_Wrapper) rules located in
    `/etc/hosts.allow` (by default all hosts will be denied access in
    `/etc/hosts.deny`, but this can be disabled by a variable).
    
    Other roles can use this role as a dependency to manage access to their own
    services (for example, `debops.mysql`, `debops.sshd`).
    
    By default, tcpwrappers will be configured to block access from everywhere
    except `localhost` (relative to remote host) and Ansible Controller.

