---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-tinc"
  git_branch: "master"
  galaxy_id: '3855'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    [tinc](http://tinc-vpn.org/) is a Virtual Private Network daemon, it can be
    used to create encrypted and tunneled connections to other hosts, forming
    a separate network, either a centralized one or a mesh.

    `debops.tinc` Ansible role allows you to install and configure a mesh VPN
    using `tinc`, including automatic public key exchange between all hosts in
    Ansble inventory, connection to external hosts and secure configuration.

