---

- name: Ensure that alternative daemons/programs are not installed
  apt:
    name: '{{ item }}'
    state: 'absent'
    purge: True
  with_flattened:
    - [ '{{ "ntpdate" if (ntp_daemon != "ntpdate") else [] }}' ]
    - [ '{{ "ntp" if (ntp_daemon != "ntpd") else [] }}' ]
    - [ '{{ "openntpd" if (ntp_daemon != "openntpd") else [] }}' ]

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - [ '{{ "ntpdate" if (ntp_daemon == "ntpdate") else [] }}' ]
    - [ '{{ "ntp" if (ntp_daemon == "ntpd") else [] }}' ]
    - [ '{{ "openntpd" if (ntp_daemon == "openntpd") else [] }}' ]

# NTPdate does not need to be configured separately as the script `/usr/sbin/ntpdate-debian`
# will pick up the configuration from `/etc/ntp.conf` when it exists.

  # Install NTPd on all hosts except inside containers
- include: ntpd.yml
  when: ntp_daemon in [ 'ntpd', 'ntpdate' ]

  # Install OpenNTPd on all hosts except inside containers
- include: openntpd.yml
  when: ntp_daemon == 'openntpd'

