---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-etherpad"
  git_branch: "master"
  galaxy_id: "1564"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

    - name:  'Robin Schneider'
      url: 'http://ypid.de/'
      email: 'ypid@riseup.net'
      twitter: 'ypid'
      github: 'ypid'

  synopsis: |
    This role installs and configures [Etherpad](http://etherpad.org/), an
    on-line multiuser collaborative text editor. It will be installed behind
    `nginx` server with MySQL as a database backend.

