---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-ifupdown"
  git_branch: "master"
  galaxy_id: "1570"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role can be used to manage network interface configuration on Debian
    and derivative operating systems. It manages configuration in
    the `/etc/network/` directory and can be used to create different
    interface layouts across the cluster.

    The `debops.ifupdown` role tries to recognize several environments (LXC
    container, OpenVZ container, system with installed NetworkManager) and can
    automatically select one of the suggested configurations. For most
    scenarios, `debops.ifupdown` will try to configure up to two network
    interfaces (non-existent interfaces are gracefully skipped) with network
    bridges attached to them, which allows to easily connect virtual machines
    or containers to the public or private network.

    In case an advanced configuration is required (more than two network
    interfaces, bonding, modem connections, NAT, etc.), you can easily override
    the automatically selected configuration using Ansible inventory. This role can
    also be used as a dependency of another role which allows for example to
    easily manage NAT networks using the `debops.subnetwork` role.

    Some features of interface declarations require additional packages.
    One of those packages is `resolvconf` (as defined in `ifupdown_packages`)
    which will start to manage your `/etc/resolv.conf` file.
