---

# Can not changed directly. To change it define apt__default_sources in your
# inventory variables (same as below).
# Then you can change the apt__default_sources_sections directly.
apt__default_sources_sections:
  - 'main'
  - 'restricted'
  - 'universe'
  - 'multiverse'

# List of default repositories for Ubuntu Linux distribution
apt__default_sources:
  - comment:  'Ubuntu Security Repository'
    mirrors:  [ 'http://security.ubuntu.com/ubuntu' ]
    releases: [ '{{ apt__sources_release_security }}' ]
    sections: '{{ apt__sources_sections|d(apt__default_sources_sections) }}'

  - comment:  'Ubuntu Package Repositories'
    releases: '{{ apt__sources_release_list }}'
    sections: '{{ apt__sources_sections|d(apt__default_sources_sections) }}'

  #- comment:  'Ubuntu Partner Repository'
  #  mirrors:  [ 'http://archive.canonical.com/ubuntu' ]
  #  releases: [ '{{ apt__sources_release }}' ]
  #  sections: [ 'partner' ]

  #- comment:  'Ubuntu Extras Repository'
  #  mirrors:  [ 'http://extras.ubuntu.com/ubuntu' ]
  #  releases: [ '{{ apt__sources_release }}' ]
  #  sections: [ 'main' ]

