---

# Can not changed directly. To change it define apt__default_sources in your
# inventory variables (same as below).
# Then you can change the apt__default_sources_sections directly.
apt__default_sources_sections:
  - 'main'
  - 'contrib'
  - 'non-free'
  - 'rpi'

# List of default repositories for Raspbian GNU/Linux
apt__default_sources:
  - comment:  'Raspbian Main Repository'
    mirrors:  [ 'http://mirrordirector.raspbian.org/raspbian/' ]
    releases: [ '{{ apt__sources_release }}' ]
    sections: '{{ apt__sources_sections|d(apt__default_sources_sections) }}'
