---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-libvirt"
  git_branch: "master"
  galaxy_id: '4554'

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.libvirt` role can be used to manage networks and storage pools defined
    in the [libvirt][] virtualization service. It's designed to be
    used either "locally", directly on a given host, or "remotely" from a central
    host through the API.

    To configure a host to provide the `libvirtd` service you can use the `debops.libvirtd`
    role.

    [libvirt]: https://libvirt.org/
