---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'type::dependency:hard' ]

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Manage local or remote libvirt instance'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.9.0'
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system
  - virtualization

