---

# --- Apt ---

# The official APT repository information.
elasticsearch_key_id: 'D88E42B4'
elasticsearch_repository: 'http://packages.elastic.co/elasticsearch'


# --- Paths ---

elasticsearch_path_conf: '/etc/elasticsearch'
elasticsearch_path_data: '/var/lib/elasticsearch'
elasticsearch_path_logs: '/var/log/elasticsearch'
elasticsearch_path_work: '/tmp/elasticsearch'
elasticsearch_path_home: '/usr/share/elasticsearch'
elasticsearch_path_plugins: '{{ elasticsearch_path_home }}/plugins'
elasticsearch_path_lib: '{{ elasticsearch_path_home }}/lib'


# --- Memory ---

elasticsearch_memory_heap_size: '{{ (ansible_memtotal_mb | int * elasticsearch_memory_heap_size_multiplier) | round | int }}m'


# --- Discovery ---

elasticsearch_discovery_multicast_port: 54328
