---

  # Because of a bug involving LXC, module "recent" from iptables and old Linux
  # 3.2 kernel we need to use newer kernel version from Debian Wheezy Backports
  # More information:
  # - http://thr3ads.net/netfilter-buglog/2011/10/1961471-Bug-759-New-iptables-m-recent-crashes-a-LXC-host-on-lxc-stop
  # - https://patchwork.kernel.org/patch/2080541/
- name: Make sure backported Linux kernel is installed
  apt:
    name: '{{ lxc_kernel_package }}'
    state: 'latest'
    install_recommends: False
  register: lxc_register_kernel_upgrade

- name: Check status of available LXC containers
  command: lxc-ls -f
  register: lxc_list_status
  when: lxc_register_kernel_upgrade is defined and lxc_register_kernel_upgrade.changed

- name: Send mail to administrator about new or updated kernel
  mail:
    from: 'root@{{ ansible_fqdn }}'
    subject: '{{ lxc_kernel_mail_subject }}'
    to: '{{ lxc_kernel_mail_to | join(",") }}'
    charset: 'utf8'
    body: '{{ lxc_kernel_mail_body }}'
  when: lxc_register_kernel_upgrade is defined and lxc_register_kernel_upgrade.changed

