---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:grub',
            'depend-of::grub', 'type::dependency:hard' ]

galaxy_info:
  author: 'Patryk Sciborek'
  description: 'Manage GRUB configuration'
  company: 'DebOps'
  license: 'GPLv3'
  min_ansible_version: '1.7.1'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  galaxy_tags:
    - system
    - boot
    - bootloader
