---

# gitlab-git-http-server is checked out based on tags instead of branches, and since we
# cannot work with tags from a bare repository, we need to work around it
# a little.

- name: Check if bare repository is cloned
  stat:
    path: '{{ gitlab_git_http_server_dest }}'
  register: gitlab_register_git_http_server_cloned

- name: Save current checkout hash for update
  shell: git rev-parse HEAD
         chdir={{ gitlab_git_http_server_dest }}
  register: gitlab_register_git_http_server_current_head
  changed_when: False
  sudo_user: '{{ gitlab_user }}'
  when: gitlab_register_git_http_server_cloned.stat.exists

- name: Change current HEAD to master in bare repository for update
  shell: git symbolic-ref HEAD refs/heads/master
         chdir={{ gitlab_git_http_server_dest }}
  changed_when: False
  sudo_user: '{{ gitlab_user }}'
  when: gitlab_register_git_http_server_cloned.stat.exists

- name: Clone gitlab-git-http-server source code
  git:
    repo: '{{ gitlab_git_http_server_repo }}'
    dest: '{{ gitlab_git_http_server_dest }}'
    bare: True
    update: True
  sudo_user: '{{ gitlab_user }}'

- name: Restore HEAD to previous checkout
  copy:
    content: '{{ gitlab_register_git_http_server_current_head.stdout }}'
    dest: '{{ gitlab_git_http_server_dest + "/HEAD" }}'
    owner: '{{ gitlab_user }}'
    group: '{{ gitlab_group }}'
    mode: '0644'
  changed_when: False
  when: gitlab_register_git_http_server_cloned.stat.exists

- name: Check if gitlab-git-http-server is checked out
  stat:
    path: '{{ gitlab_git_http_server_checkout }}'
  register: gitlab_register_git_http_server_directory

- name: Create gitlab-git-http-server checkout directory
  file:
    path: '{{ gitlab_git_http_server_checkout }}'
    state: 'directory'
    owner: '{{ gitlab_user }}'
    group: '{{ gitlab_group }}'
    mode: '0755'

- name: Prepare gitlab-git-http-server worktree
  copy:
    content: 'gitdir: {{ gitlab_git_http_server_dest }}'
    dest: '{{ gitlab_git_http_server_checkout + "/.git" }}'
    owner: '{{ gitlab_user }}'
    group: '{{ gitlab_group }}'
    mode: '0644'

- name: Get currently checked out git tag
  shell: GIT_WORK_TREE={{ gitlab_git_http_server_checkout }} git describe --tags
         chdir={{ gitlab_git_http_server_dest }}
  sudo_user: '{{ gitlab_user }}'
  register: gitlab_register_git_http_server_target_tag
  changed_when: gitlab_register_git_http_server_target_tag.stdout != gitlab_version_map[gitlab_version].git_http_server

- name: Checkout gitlab-git-http-server
  shell: GIT_WORK_TREE={{ gitlab_git_http_server_checkout }} git checkout -f {{ gitlab_version_map[gitlab_version].git_http_server }}
         chdir={{ gitlab_git_http_server_dest }}
  sudo_user: '{{ gitlab_user }}'
  register: gitlab_register_git_http_server_checkout
  when: (gitlab_version_map[gitlab_version].git_http_server != gitlab_register_git_http_server_target_tag.stdout) or not gitlab_register_git_http_server_cloned.stat.exists

- name: Install go packages
  apt:
    name: 'golang-go'
    state: 'latest'
    install_recommends: False

- name: Setup gitlab-git-http-server
  shell: make chdir={{ gitlab_git_http_server_checkout }}
  sudo_user: '{{ gitlab_user }}'
  when: gitlab_register_git_http_server_checkout is defined and gitlab_register_git_http_server_checkout.changed

