---

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_flattened:
    - gitlab_packages
    - gitlab_database_packages[gitlab_database]

- name: Create GitLab system group
  group:
    name: '{{ gitlab_group }}'
    system: True
    state: 'present'

- name: Create GitLab user
  user:
    name: '{{ gitlab_user }}'
    group: '{{ gitlab_group }}'
    home: '{{ gitlab_home }}'
    comment: 'GitLab'
    groups: '{{ gitlab_user_append_groups | join(",") | default(omit) }}'
    append: True
    system: True
    state: 'present'

- name: Create GitLab application directory
  file:
    path: '{{ gitlab_app_root_path }}'
    state: 'directory'
    owner: '{{ gitlab_user }}'
    group: '{{ gitlab_group }}'
    mode: '0750'

- name: Allow access to GitLab application directory by the webserver
  acl:
    name: '{{ gitlab_app_root_path }}'
    entity: 'www-data'
    etype: 'group'
    permissions: 'x'
    state: 'present'
  when: gitlab_support_filesystem_acl

- name: Configure ~/.gitconfig
  template:
    src: 'var/local/git/gitconfig.j2'
    dest: '{{ gitlab_home + "/.gitconfig" }}'
    owner: '{{ gitlab_user }}'
    group: '{{ gitlab_group }}'
    mode: '0644'

- include: configure_gitlab-shell.yml

- include: configure_gitlab-git-http-server.yml
  when: gitlab_enable_git_http_server

- include: configure_gitlab-workhorse.yml
  when: gitlab_enable_gitlab_workhorse

- include: configure_gitlab_ce.yml

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save information about GitLab CE in Ansible Facts
  template:
    src: 'etc/ansible/facts.d/gitlab.fact.j2'
    dest: '/etc/ansible/facts.d/gitlab.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'

- include: ldap_account.yml
  when: gitlab_ldap_enable

