---

- include: core.yml

- name: Common configuration for all hosts
  hosts: [ 'debops_all_hosts', '!debops_no_common' ]
  gather_facts: True
  become: True

  roles:

    - role: debops.pki/env
      tags: [ 'role::pki', 'role::pki:secret', 'role::secret' ]

    - role: debops.secret
      tags: [ 'role::secret', 'role::pki', 'role::pki:secret' ]
      secret_directories:
        - '{{ pki_env_secret_directories }}'

    - role: debops.apt_preferences
      tags: [ 'apt_preferences', 'role::apt_preferences' ]
      apt_preferences__dependent_list:
        - '{{ sshd__apt_preferences__dependent_list }}'
        - '{{ apt__apt_preferences__dependent_list }}'
        - '{{ apt_install__apt_preferences__dependent_list }}'
        - '{{ rsyslog__apt_preferences__dependent_list }}'

    - role: debops.atd
      tags: [ 'role::atd' ]

    - role: debops.dhparam
      tags: [ 'role::dhparam' ]

    - role: debops.pki
      tags: [ 'role::pki' ]

    - role: debops.apt
      tags: [ 'role::apt' ]

    - role: debops.apt_install
      tags: [ 'role::apt_install' ]

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ rsyslog__etc_services__dependent_list }}'

    - role: debops.logrotate
      tags: [ 'role::logrotate' ]
      logrotate__dependent_config:
        - '{{ rsyslog__logrotate__dependent_config }}'

    - role: debops.auth
      tags: [ 'role::auth' ]

    - role: debops.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ ntp__ferm__dependent_rules }}'
        - '{{ postfix_ferm_dependent_rules }}'
        - '{{ rsyslog__ferm__dependent_rules }}'
        - '{{ sshd__ferm__dependent_rules }}'

    - role: debops.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers_dependent_allow:
        - '{{ sshd__tcpwrappers__dependent_allow }}'

    - role: debops.ntp
      tags: [ 'role::ntp' ]

    - role: debops.ifupdown
      tags: [ 'role::ifupdown' ]

    - role: debops.console
      tags: [ 'role::console' ]

    - role: debops.postfix
      tags: [ 'role::postfix' ]

    - role: debops.rsyslog
      tags: [ 'role::rsyslog' ]

    - role: debops.unattended_upgrades
      tags: [ 'role::unattended_upgrades' ]

    - role: debops.users
      tags: [ 'role::users' ]

    - role: debops.sshkeys
      tags: [ 'role::sshkeys' ]

    - role: debops.sshd
      tags: [ 'role::sshd' ]

    - role: debops.resources
      tags: [ 'role::resources' ]

