---

# Configuration for nginx proxy
rstudio_server_nginx_server:

  by_role: 'debops.rstudio_server'
  enabled: True
  name: '{{ rstudio_server_domains }}'

  access_policy: '{{ rstudio_server_nginx_access_policy }}'
  auth_basic_realm: '{{ rstudio_server_nginx_auth_realm }}'

  options: |
    client_max_body_size {{ rstudio_server_upload_size }};

  location:
    '/': |
      proxy_pass http://localhost:{{ rstudio_server_port }};
      proxy_redirect http://localhost:{{ rstudio_server_port }}/ $scheme://$host/;

