---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-gitlab"
  git_branch: "master"
  galaxy_id: "1566"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    This role installs [GitLab](https://about.gitlab.com/), an Open Source
    GitHub clone.  `debops.gitlab` role will also automatically update
    installed GitLab instance if new patches are pushed to the repository.
    
    You can also use this role to upgrade an already installed GitLab instance
    to new version when support for it becomes available (new GitLab version is
    released on 22nd of each month, usually `debops.gitlab` role is updated
    to support new version shortly after that).

