---

- name: Create farm base directory
  file:
    path: '{{ dokuwiki_farm_path }}'
    state: 'directory'
    owner: '{{ dokuwiki_user }}'
    group: '{{ dokuwiki_webserver_user }}'
    mode: '0750'

- name: Create farm animal directories
  copy:
    src: 'srv/www/dokuwiki/farm/animal/'
    dest: '{{ dokuwiki_farm_path + "/" + item + "/" }}'
    owner: '{{ dokuwiki_user }}'
    group: '{{ dokuwiki_webserver_user }}'
    force: False
  with_items: dokuwiki_farm_animals
  when: dokuwiki_farm_animals is defined and dokuwiki_farm_animals

