---

# Filepath of the API key file
etherpad_api_key_file: '{{ etherpad_home + "/" + etherpad_repository }}/APIKEY.txt'

# git repository address and name
etherpad_source_address: 'https://github.com/ether'
etherpad_repository: 'etherpad-lite'


# Etherpad database configuration map
etherpad_database_config:
  dirty:
    filename: 'var/dirty.db'
  sqlite:
    filename: 'var/sqlite.db'
  mysql:
    hostname: '{{ etherpad_database_server }}'
    username: '{{ etherpad_database_user }}'
    database: '{{ etherpad_database_name }}'
    password: '{{ etherpad_database_password }}'
    socket:   '/var/run/mysqld/mysqld.sock'
    port:     '3306'
  postgresql:
    hostname: 'localhost'
    username: '{{ etherpad_database_user }}'
    database: '{{ etherpad_database_name }}'
    password: '{{ etherpad_database_password }}'
    socket:   '/var/run/postgresql'
    port:     '5432'

# nginx upstream configuration for Etherpad
etherpad_nginx_upstream:
  enabled: True
  name: '{{ etherpad_system_name }}'
  server: '127.0.0.1:{{ etherpad_port }}'

# A template for nginx server for most common location
etherpad_nginx_server_proxy_template: |
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_buffering off;
  proxy_pass http://{{ etherpad_system_name }};

# nginx server main configuration
etherpad_nginx_server:
  by_role: 'debops.etherpad'
  enabled: True
  default: False
  favicon: False
  name: '{{ etherpad_domain }}'

  location:

    # Allow normal files to pass through
    '~ ^/(locales/|locales.json|admin/|static/|pluginfw/|javascripts/|socket.io/|ep/|minified/|api/|ro/|error/|jserror/|favicon.ico|robots.txt)': '{{ etherpad_nginx_server_proxy_template }}'

    # Redirect to force /p/* URLs to the friendly version
    '/p/': |
      rewrite ^/p/(.*) /$1 redirect;

    # Handle redirects
    '/redirect': '{{ etherpad_nginx_server_proxy_template }}'

    # Match the home page
    '~ ^/$': '{{ etherpad_nginx_server_proxy_template }}'

    # Handle pad URLs here
    '/': |
      rewrite ^/admin(.*) /admin/$1 redirect;
      rewrite ^/list(.*) /list break;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_buffering off;
      proxy_pass http://{{ etherpad_system_name }}/p/;
      proxy_redirect / /p/;

  location_allow:

    '~ ^/(locales/|locales.json|admin/|static/|pluginfw/|javascripts/|socket.io/|ep/|minified/|api/|ro/|error/|jserror/|favicon.ico|robots.txt)': '{{ etherpad_allow }}'

    '/p/': '{{ etherpad_allow }}'

    '/redirect': '{{ etherpad_allow }}'

    '~ ^/$': '{{ etherpad_allow }}'

    '/': '{{ etherpad_allow }}'


