---

dependencies:

  - role: debops.etc_services
    etc_services_dependent_list: '{{ stunnel_services }}'

  - role: debops.ferm
    ferm_input_dependent_list: '{{ stunnel_services }}'

  - role: debops.tcpwrappers
    tcpwrappers_dependent_allow: '{{ stunnel_services }}'

galaxy_info:
  author: 'Maciej Delmanowski'
  description: 'Create an encrypted TCP tunnel between two hosts using stunnel and SSL'
  company: 'DebOps'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.8.0'
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - quantal
    - raring
    - saucy
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - system
  - networking

