---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-ruby"
  git_branch: "master"
  galaxy_id: "1595"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    The `debops.ruby` role installs the selected Ruby version via the APT package manager.
    By default APT picks the Ruby packages to install automatically – if you
    have backported Ruby 2.1 packages, they will be installed if available; if
    you don't have them, `debops.ruby` will install current Ruby packages
    available on your system.
    
    If you want to install Ruby 2.1 packages on Debian Wheezy, set
    `ruby_version: 'backport'` in your inventory and this role will use
    the `debops.backporter` role to automatically backport all required packages
    from Debian Jessie. These packages will be installed on the build host and
    uploaded to Ansible Controller to a specific directory, where
    `debops.reprepro` role can find them and automatically import them to local
    APT repository, at which point these packages will become available to all
    hosts in a cluster.
    
    This role will also install gems from [RubyGems](https://rubygems.org/)
    specified in a list.

