---

ansigenome_info:
  github_url: "https://github.com/debops/ansible-nfs"
  git_branch: "master"
  galaxy_id: "1579"

  travis: True

  license_url: 'https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)'

  authors:
    - name:  'Maciej Delmanowski'
      url: ''
      email: 'drybjed@gmail.com'
      twitter: 'drybjed'
      github: 'drybjed'

  synopsis: |
    `debops.nfs` role manages a NFS server. It can automatically configure
    ``iptables`` firewall using
    [debops.ferm](https://github.com/debops/ansible-ferm/) role and reserve
    ports for services required by NFS using
    [debops.etc_services](https://github.com/debops/ansible-etc_services/)
    role. You can also modify default list of exported directories and use host
    Access Control Lists using Ansible inventory. Clients which connect to NFS
    are configured separately.

