---

dependencies:

  - role: debops.secret
    tags: [ 'depend::secret', 'depend::secret:preseed', 'depend-of::preseed', 'type::dependency:hard' ]

  - role: debops.nginx
    nginx_servers:
      - '{{ preseed_nginx_server_http  }}'
      - '{{ preseed_nginx_server_https }}'
    tags: [ 'depend::nginx', 'depend::nginx:preseed', 'depend-of::preseed', 'type::dependency' ]
    when: (preseed_dependencies|d() | bool)

galaxy_info:

  company: 'DebOps'
  author: 'Maciej Delmanowski'
  description: 'Provide Debian Preseed configuration files over HTTP'
  license: 'GNU General Public License v3'
  min_ansible_version: '1.7.0'

  platforms:

    - name: Ubuntu
      versions:
        - precise
        - quantal
        - raring
        - saucy
        - trusty

    - name: Debian
      versions:
        - wheezy
        - jessie

  galaxy_tags:
    - system
    - installation
    - deployment
